- .github/workflows/ci.yml
- sample/app/build.gradle
> Disable the release build type in the sample application. 

- .editorconfig
- .github/workflows/ci.yml
- compiler/src/main/java/com/squareup/anvil/compiler/InterfaceMerger.kt
- compiler/src/main/java/com/squareup/anvil/compiler/ModuleMerger.kt
- compiler/src/test/java/com/squareup/anvil/compiler/ModuleMergerTest.kt
- gradle-plugin/src/main/java/com/squareup/anvil/plugin/AnvilPlugin.kt
- gradle-plugin/src/main/java/com/squareup/anvil/plugin/AnvilSubplugin.kt
- gradle-plugin/src/main/java/com/squareup/anvil/plugin/IncrementalSignal.kt
Before it accidentally didn't run.
> Run KtLint in the module :gradle-plugin in CI. 

- annotations/src/main/java/com/squareup/anvil/annotations/ContributesBinding.kt
- compiler/src/main/java/com/squareup/anvil/compiler/AnvilComponentRegistrar.kt
- compiler/src/main/java/com/squareup/anvil/compiler/ClassScanner.kt
- compiler/src/main/java/com/squareup/anvil/compiler/Utils.kt
- compiler/src/main/java/com/squareup/anvil/compiler/codegen/ContributesBindingGenerator.kt
- compiler/src/main/java/com/squareup/anvil/compiler/codegen/PsiUtils.kt
- compiler/src/test/java/com/squareup/anvil/compiler/TestUtils.kt
- compiler/src/test/java/com/squareup/anvil/compiler/codegen/ContributesBindingGeneratorTest.kt
- compiler/src/test/java/com/squareup/anvil/compiler/codegen/ContributesToGeneratorTest.kt
This PR only adds the annotation and one functionality in order to make the feature work. I thought it would be easier to review this way.
> Introduce the @ContributesBinding annotation

- compiler/src/main/java/com/squareup/anvil/compiler/ClassScanner.kt
- compiler/src/main/java/com/squareup/anvil/compiler/InterfaceMerger.kt
- compiler/src/main/java/com/squareup/anvil/compiler/ModuleMerger.kt
- compiler/src/main/java/com/squareup/anvil/compiler/Utils.kt
> Clean up some helper functions

- gradle-plugin/src/main/java/com/squareup/anvil/plugin/AnvilSubplugin.kt
Override the Kotlin compilation task inputs to avoid build cache misses on different machines.
Fixes #65
> Override the Kotlin compilation task inputs

- compare_size.sh
- dependencies.gradle
- integration-tests/library/build.gradle
- integration-tests/library/src/main/java/com/squareup/anvil/test/Modules.kt
- sample/library/build.gradle
> Add a script that compares the size of Dagger and Anvil generated code.

- compiler/src/main/java/com/squareup/anvil/compiler/codegen/dagger/KotlinPoet.kt
- compiler/src/test/java/com/squareup/anvil/compiler/dagger/InjectConstructorFactoryGeneratorTest.kt
> Support classes starting with a lowercase character.

- compiler/src/main/java/com/squareup/anvil/compiler/codegen/dagger/ProvidesMethodFactoryGenerator.kt
Generate an object implementing the Factory interface rather than a class with a companion object when a provider method doesn't have any parameters and the Dagger module is stateless.
This reduces the bytecode size #76.
Old report:
```
JAR   │ old      │ new      │ diff
───────┼──────────┼──────────┼──────────
class │ 29.3 KiB │ 36.8 KiB │ +7.5 KiB
other │    476 B │    476 B │      0 B
───────┼──────────┼──────────┼──────────
total │ 29.7 KiB │ 37.2 KiB │ +7.5 KiB
CLASSES │ old │ new │ diff
─────────┼─────┼─────┼──────────────
classes │  28 │  29 │  +1 (+4 -3)
methods │  74 │  89 │ +15 (+24 -9)
fields │  23 │  27 │  +4 (+7 -3)
```
New report:
```
JAR   │ old      │ new      │ diff
───────┼──────────┼──────────┼──────────
class │ 29.3 KiB │ 34.8 KiB │ +5.5 KiB
other │    476 B │    476 B …
```
> Generate an object implementing the Factory interface

- compiler/src/main/java/com/squareup/anvil/compiler/codegen/PsiUtils.kt
- compiler/src/main/java/com/squareup/anvil/compiler/codegen/dagger/MembersInjectorGenerator.kt
- compiler/src/test/java/com/squareup/anvil/compiler/dagger/MembersInjectorGeneratorTest.kt
> Support generic classes that use field injection.

- compiler/src/main/java/com/squareup/anvil/compiler/codegen/dagger/MembersInjectorGenerator.kt
- compiler/src/test/java/com/squareup/anvil/compiler/dagger/MembersInjectorGeneratorTest.kt
> Support classes with multiple generic parameters for field injection

- compiler/src/main/java/com/squareup/anvil/compiler/InterfaceMerger.kt
- compiler/src/main/java/com/squareup/anvil/compiler/ModuleMerger.kt
- compiler/src/test/java/com/squareup/anvil/compiler/InterfaceMergerTest.kt
- compiler/src/test/java/com/squareup/anvil/compiler/MergeModulesTest.kt
- compiler/src/test/java/com/squareup/anvil/compiler/ModuleMergerTest.kt
Verify that the scope of replaced and excluded classes matches the scope of the merged target. Throw an error otherwise.
While it technically would be possible to support this case it leads to very confusing results and hard to debug missing bindings.
Fixes #107
> Verify scopes

- compiler/src/main/java/com/squareup/anvil/compiler/codegen/KotlinPoet.kt
- compiler/src/main/java/com/squareup/anvil/compiler/codegen/PsiUtils.kt
- compiler/src/main/java/com/squareup/anvil/compiler/codegen/dagger/InjectConstructorFactoryGenerator.kt
- compiler/src/test/java/com/squareup/anvil/compiler/dagger/InjectConstructorFactoryGeneratorTest.kt
Fixes #111 
Feedbacks very appreciated, I don't have much experience with Kotlin psi 😅
> Support classes with type parameters and @Inject constructor

- compiler/src/main/java/com/squareup/anvil/compiler/codegen/PsiUtils.kt
- compiler/src/test/java/com/squareup/anvil/compiler/dagger/ProvidesMethodFactoryGeneratorTest.kt
> Support named imports in @Provides annotated methods

- compiler/src/main/java/com/squareup/anvil/compiler/codegen/KotlinPoet.kt
- compiler/src/main/java/com/squareup/anvil/compiler/codegen/PsiUtils.kt
- compiler/src/main/java/com/squareup/anvil/compiler/codegen/dagger/InjectConstructorFactoryGenerator.kt
- compiler/src/test/java/com/squareup/anvil/compiler/dagger/InjectConstructorFactoryGeneratorTest.kt
> Support constructor injection for classes with bounded type parameters

- compiler/src/main/java/com/squareup/anvil/compiler/codegen/PsiUtils.kt
- compiler/src/test/java/com/squareup/anvil/compiler/dagger/ProvidesMethodFactoryGeneratorTest.kt
- compiler/src/test/java/com/squareup/anvil/compiler/dagger/TestClasses.kt
> Fix incorrect named imports resolution.

- compiler/src/main/java/com/squareup/anvil/compiler/codegen/PsiUtils.kt
- compiler/src/main/java/com/squareup/anvil/compiler/codegen/dagger/ProvidesMethodFactoryGenerator.kt
- compiler/src/test/java/com/squareup/anvil/compiler/dagger/ProvidesMethodFactoryGeneratorTest.kt
> Support property as providers in Dagger modules.

- compiler/src/main/java/com/squareup/anvil/compiler/codegen/KotlinPoet.kt
- compiler/src/test/java/com/squareup/anvil/compiler/TestUtils.kt
- compiler/src/test/java/com/squareup/anvil/compiler/dagger/AssistedFactoryGeneratorTest.kt
- compiler/src/test/java/com/squareup/anvil/compiler/dagger/AssistedInjectGeneratorTest.kt
> Support nullable parameters for assisted injection properly.

- .github/workflows/ci.yml
- compiler/src/main/java/com/squareup/anvil/compiler/IrUtils.kt
- dependencies.gradle
- gradle-plugin/build.gradle
- gradle-plugin/gradle/wrapper/gradle-wrapper.properties
- gradle-plugin/src/main/java/com/squareup/anvil/plugin/AnvilPlugin.kt
- gradle/wrapper/gradle-wrapper.properties
> Upgrade Anvil to Kotlin 1.4.30.

- compiler/src/main/java/com/squareup/anvil/compiler/codegen/PsiUtils.kt
- compiler/src/test/java/com/squareup/anvil/compiler/dagger/ProvidesMethodFactoryGeneratorTest.kt
Until now we ignored the package and only evaluated the class name, which lead to wrong imports.
Fixes #198
> Handle fully qualified names with generic types properly. 

- compiler/src/main/java/com/squareup/anvil/compiler/codegen/BindingModuleGenerator.kt
- compiler/src/main/java/com/squareup/anvil/compiler/codegen/CodeGenerator.kt
- compiler/src/main/java/com/squareup/anvil/compiler/codegen/ContributesBindingGenerator.kt
- compiler/src/main/java/com/squareup/anvil/compiler/codegen/ContributesToGenerator.kt
- compiler/src/main/java/com/squareup/anvil/compiler/codegen/PrivateCodeGenerator.kt
- compiler/src/main/java/com/squareup/anvil/compiler/codegen/PsiUtils.kt
- compiler/src/main/java/com/squareup/anvil/compiler/codegen/dagger/AssistedFactoryGenerator.kt
- compiler/src/main/java/com/squareup/anvil/compiler/codegen/dagger/AssistedInjectGenerator.kt
- compiler/src/main/java/com/squareup/anvil/compiler/codegen/dagger/InjectConstructorFactoryGenerator.kt
- compiler/src/main/java/com/squareup/anvil/compiler/codegen/dagger/MembersInjectorGenerator.kt
- compiler/src/main/java/com/squareup/anvil/compiler/codegen/dagger/ProvidesMethodFactoryGenerator.kt
This is a clean up PR. I believe this way the generated code is easier to read, because proper imports are used.
> Use Kotlin Poet for generating the hints. 

- CHANGELOG.md
- README.md
- dependencies.gradle
> Add documentation for contributed multibindings.

- compiler/src/main/java/com/squareup/anvil/compiler/codegen/PsiUtils.kt
- compiler/src/test/java/com/squareup/anvil/compiler/dagger/InjectConstructorFactoryGeneratorTest.kt
> fix factory generation when injecting an inner class with a generic parameter

- compiler/src/main/java/com/squareup/anvil/compiler/codegen/CodeGenerator.kt
- compiler/src/main/java/com/squareup/anvil/compiler/codegen/dagger/AssistedFactoryGenerator.kt
- compiler/src/test/java/com/squareup/anvil/compiler/dagger/AssistedFactoryGeneratorTest.kt
> make generated assisted factories match interface function name

- compiler/src/main/java/com/squareup/anvil/compiler/codegen/PsiUtils.kt
- compiler/src/main/java/com/squareup/anvil/compiler/codegen/dagger/AssistedFactoryGenerator.kt
- compiler/src/main/java/com/squareup/anvil/compiler/codegen/dagger/AssistedInjectGenerator.kt
- compiler/src/main/java/com/squareup/anvil/compiler/codegen/dagger/InjectConstructorFactoryGenerator.kt
- compiler/src/test/java/com/squareup/anvil/compiler/dagger/AssistedFactoryGeneratorTest.kt
- compiler/src/test/java/com/squareup/anvil/compiler/dagger/AssistedInjectGeneratorTest.kt
- compiler/src/test/java/com/squareup/anvil/compiler/dagger/InjectConstructorFactoryGeneratorTest.kt
> fix where clauses and generic type bounds in injected classes

- build.gradle
- compiler/src/test/java/com/squareup/anvil/compiler/dagger/AssistedInjectGeneratorTest.kt
- dependencies.gradle
- gradle-plugin/build.gradle
Gradle often times is a terrible tool and wants you to hate it.
> Enable the check to make compile warnings errors again. 

- compiler/src/main/java/com/squareup/anvil/compiler/codegen/PsiUtils.kt
- compiler/src/main/java/com/squareup/anvil/compiler/codegen/dagger/MembersInjectorGenerator.kt
- compiler/src/test/java/com/squareup/anvil/compiler/dagger/MembersInjectorGeneratorTest.kt
> Copy over qualifiers in member injecttion

- compiler/src/main/java/com/squareup/anvil/compiler/AnvilCommandLineProcessor.kt
- compiler/src/main/java/com/squareup/anvil/compiler/AnvilComponentRegistrar.kt
- compiler/src/main/java/com/squareup/anvil/compiler/codegen/dagger/AnvilMergeAnnotationDetectorCheck.kt
- compiler/src/test/java/com/squareup/anvil/compiler/TestUtils.kt
- compiler/src/test/java/com/squareup/anvil/compiler/dagger/AnvilMergeAnnotationDetectorCheckTest.kt
- gradle-plugin/src/main/java/com/squareup/anvil/plugin/AnvilExtension.kt
- gradle-plugin/src/main/java/com/squareup/anvil/plugin/AnvilPlugin.kt
> Implement generation-only mode

- compiler/src/main/java/com/squareup/anvil/compiler/Utils.kt
- compiler/src/main/java/com/squareup/anvil/compiler/codegen/BindingModuleGenerator.kt
- compiler/src/test/java/com/squareup/anvil/compiler/codegen/BindingModulePriorityTest.kt
> Respect qualifiers when checking whether there is a duplicate binding.

- gradle-plugin/src/main/java/com/squareup/anvil/plugin/AnvilPlugin.kt
> Support Kotlin multiplatform projects.

- gradle-plugin/src/main/java/com/squareup/anvil/plugin/AnvilPlugin.kt
> Add anvil configuration for picking up custom code generators

- gradle-plugin/src/main/java/com/squareup/anvil/plugin/AnvilExtension.kt
- gradle-plugin/src/main/java/com/squareup/anvil/plugin/AnvilPlugin.kt
Followup from https://github.com/square/anvil/pull/284#discussion_r640868003
> Use conventions in Gradle extension properties

- .github/workflows/ci.yml
- compiler-utils/src/main/java/com/squareup/anvil/compiler/internal/CompilerUtils.kt
- compiler-utils/src/testFixtures/java/com/sqareup/anvil/compiler/internal/testing/TestUtils.kt
- compiler/src/main/java/com/squareup/anvil/compiler/codegen/BindingModuleGenerator.kt
- compiler/src/main/java/com/squareup/anvil/compiler/codegen/dagger/InjectConstructorFactoryGenerator.kt
- compiler/src/main/java/com/squareup/anvil/compiler/codegen/dagger/MembersInjectorGenerator.kt
- compiler/src/main/java/com/squareup/anvil/compiler/codegen/dagger/ProvidesMethodFactoryGenerator.kt
- compiler/src/test/java/com/squareup/anvil/compiler/TestUtils.kt
- compiler/src/test/java/com/squareup/anvil/compiler/dagger/MembersInjectorGeneratorTest.kt
- dependencies.gradle
- gradle-plugin/build.gradle
- gradle-plugin/generate_build_properties.gradle
- sample/library/src/main/java/com/squareup/anvil/sample/Description.kt
I will wait until I bump the version. I don't know if the plugin would be backwards compatible. I need to test.
> Kotlin `1.5.10`

- gradle-plugin/src/main/java/com/squareup/anvil/plugin/AnvilPlugin.kt
Builds weren't incremental due to:
```
The task was not up-to-date because of the following reasons:
Additional action for task ':sample:library:compileKotlin': was implemented by the Java lambda 'com.squareup.anvil.plugin.AnvilPlugin$$Lambda$7578/0x0000000801769440'. Using Java lambdas is not supported, use an (anonymous) inner class instead.
```
https://scans.gradle.com/s/ppwb2psllveks/timeline?details=j62m2xx52wwxy
Gradle is love.
> Fix incremental Gradle builds. 

- compiler-utils/src/main/java/com/squareup/anvil/compiler/internal/PsiUtils.kt
- compiler/src/main/java/com/squareup/anvil/compiler/codegen/ContributesBindingGenerator.kt
- integration-tests/code-generator/src/main/java/com/squareup/anvil/test/TestCodeGenerator.kt
That makes the situation for #310 a little better, but doesn't resolve it yet.
> Try to skip resolving the class descriptor while checking the super type in ContributesBindingGenerator

- gradle-plugin/src/main/java/com/squareup/anvil/plugin/AnvilPlugin.kt
- integration-tests/mpp/android-module/src/androidDebug/kotlin/com/squareup/anvil/mpp/DebugDependency.kt
- integration-tests/mpp/android-module/src/androidTestDebug/kotlin/com/squareup/anvil/mpp/DebugDependencyTest.kt
> make non-test variants extend common anvil config

- compiler-utils/src/main/java/com/squareup/anvil/compiler/internal/PsiUtils.kt
- compiler/src/main/java/com/squareup/anvil/compiler/codegen/BindingModuleGenerator.kt
- compiler/src/main/java/com/squareup/anvil/compiler/codegen/PsiUtils.kt
- integration-tests/code-generator-tests/src/test/java/com/squareup/anvil/test/GeneratedCodeTest.kt
- integration-tests/code-generator/src/main/java/com/squareup/anvil/test/TestCodeGenerator.kt
> use Psi APIs to resolve scope and exclude arguments

- compiler/src/main/java/com/squareup/anvil/compiler/codegen/BindingModuleGenerator.kt
- compiler/src/test/java/com/squareup/anvil/compiler/ModuleMergerTest.kt
- compiler/src/test/java/com/squareup/anvil/compiler/codegen/BindingModuleGeneratorTest.kt
Ensure that excluded bindings and modules are only excluded for the specific component that merges a scope and not all components merging the same scope.
Fixes #321
> Test merging multiple components with the same scope

- gradle-plugin/src/main/java/com/squareup/anvil/plugin/AnvilPlugin.kt
This is a regression in `2.3.1`.
> Disable precise java tracking for the stub generating Kotlin compile task.

- README.md
Some of our open source repos' readmes start with silly fake quotes. I came up with one for Anvil, feel free to reject this PR without cause.
> Add a README quote joke

- compiler/src/main/java/com/squareup/anvil/compiler/codegen/CodeGenerationExtension.kt
- compiler/src/main/java/com/squareup/anvil/compiler/codegen/RealAnvilModuleDescriptor.kt
This could potentially help with #310 and #326.
> Only call private code generators once after all other code generators are done

- dependencies.gradle
For [Gradle 7.1 support](https://plugins.gradle.org/plugin/com.gradle.plugin-publish/0.15.0)
> Update Gradle publish plugin

- compiler/src/main/java/com/squareup/anvil/compiler/codegen/dagger/InjectConstructorFactoryGenerator.kt
- compiler/src/test/java/com/squareup/anvil/compiler/dagger/InjectConstructorFactoryGeneratorTest.kt
> Don't generate a singleton factory (object), if the class with the inject constructor has any type parameter

- compiler/src/main/java/com/squareup/anvil/compiler/codegen/dagger/AssistedInjectGenerator.kt
- compiler/src/main/java/com/squareup/anvil/compiler/codegen/dagger/InjectConstructorFactoryGenerator.kt
- compiler/src/main/java/com/squareup/anvil/compiler/codegen/dagger/MembersInjectionUtils.kt
- compiler/src/main/java/com/squareup/anvil/compiler/codegen/dagger/MembersInjectorGenerator.kt
- compiler/src/test/java/com/squareup/anvil/compiler/dagger/MembersInjectorGeneratorTest.kt
> Fix member injection from factories on property setters

- compiler/src/main/java/com/squareup/anvil/compiler/codegen/dagger/MembersInjectorGenerator.kt
- compiler/src/test/java/com/squareup/anvil/compiler/dagger/MembersInjectorGeneratorTest.kt
> fix member injector generation for Provider<Lazy<T>>

- compiler-utils/src/main/java/com/squareup/anvil/compiler/internal/PsiUtils.kt
- compiler/src/test/java/com/squareup/anvil/compiler/dagger/InjectConstructorFactoryGeneratorTest.kt
> Prefer Kotlin collection types when Java collections are imported through a star import

- compiler-utils/src/main/java/com/squareup/anvil/compiler/internal/ClassReference.kt
- compiler-utils/src/main/java/com/squareup/anvil/compiler/internal/CompilerUtils.kt
- compiler-utils/src/main/java/com/squareup/anvil/compiler/internal/FqName.kt
- compiler-utils/src/main/java/com/squareup/anvil/compiler/internal/KotlinPoetUtils.kt
- compiler-utils/src/main/java/com/squareup/anvil/compiler/internal/PsiUtils.kt
- compiler/src/main/java/com/squareup/anvil/compiler/ClassScanner.kt
- compiler/src/main/java/com/squareup/anvil/compiler/InterfaceMerger.kt
- compiler/src/main/java/com/squareup/anvil/compiler/ModuleMerger.kt
- compiler/src/main/java/com/squareup/anvil/compiler/Utils.kt
- compiler/src/main/java/com/squareup/anvil/compiler/codegen/BindingModuleGenerator.kt
- compiler/src/main/java/com/squareup/anvil/compiler/codegen/DescriptorUtils.kt
- compiler/src/main/java/com/squareup/anvil/compiler/codegen/dagger/AssistedFactoryGenerator.kt
- compiler/src/test/java/com/squareup/anvil/compiler/dagger/AssistedFactoryGeneratorTest.kt
- integration-tests/code-generator/src/main/java/com/squareup/anvil/test/TestCodeGenerator.kt
> support generic supers for assisted factories when the assisted factory interface is generated

- compiler-utils/src/main/java/com/squareup/anvil/compiler/internal/ClassReference.kt
- compiler-utils/src/main/java/com/squareup/anvil/compiler/internal/PsiUtils.kt
- compiler/src/main/java/com/squareup/anvil/compiler/Utils.kt
- compiler/src/main/java/com/squareup/anvil/compiler/codegen/BindingModuleGenerator.kt
- compiler/src/main/java/com/squareup/anvil/compiler/codegen/ContributedBinding.kt
- compiler/src/main/java/com/squareup/anvil/compiler/codegen/ContributesBindingGenerator.kt
- compiler/src/main/java/com/squareup/anvil/compiler/codegen/DescriptorUtils.kt
- compiler/src/main/java/com/squareup/anvil/compiler/codegen/PsiUtils.kt
- integration-tests/code-generator-tests/src/test/java/com/squareup/anvil/test/GeneratedCodeTest.kt
- integration-tests/code-generator/src/main/java/com/squareup/anvil/test/TestCodeGenerator.kt
> fall back to PSI parsing for BindingModuleGenerator

- gradle-plugin/src/main/java/com/squareup/anvil/plugin/AnvilExtension.kt
- gradle-plugin/src/main/java/com/squareup/anvil/plugin/AnvilPlugin.kt
- gradle-plugin/src/main/java/com/squareup/anvil/plugin/VariantFilter.kt
https://user-images.githubusercontent.com/1558045/140219280-ec7eb47b-6fe7-4a7a-9c0a-f92e4cf1d98c.mov
> Add an option in the Anvil DSL to sync generated sources in the IDE.

- gradle-plugin/src/main/java/com/squareup/anvil/plugin/AnvilPlugin.kt
https://user-images.githubusercontent.com/1558045/140458356-c110dcc6-7ebb-4ce3-9b6a-97effdd1b49e.mov
> Support the AGP and Android projects properly when syncing sources in the IDE

- compiler-utils/src/main/java/com/squareup/anvil/compiler/internal/PsiUtils.kt
- compiler/src/main/java/com/squareup/anvil/compiler/codegen/dagger/AssistedFactoryGenerator.kt
- compiler/src/test/java/com/squareup/anvil/compiler/dagger/AssistedFactoryGeneratorTest.kt
> Check for function bodies in assisted functions

- compiler/src/main/java/com/squareup/anvil/compiler/codegen/dagger/AssistedFactoryGenerator.kt
- compiler/src/test/java/com/squareup/anvil/compiler/dagger/AssistedFactoryGeneratorTest.kt
When there are multiple abstract methods in an assisted factory.
> Check for the correct reported function names

- .github/workflows/ci.yml
- dependencies.gradle
Quite a few more CI actions because of that, but they're all very fast.
> Test multiple AGP versions in CI.

- annotations/src/main/java/com/squareup/anvil/annotations/ContributesSubcomponent.kt
Hi folks, I'm giving the new annotation I try. The documentation did not quite make sense to me. I think it should be ActivitySubcomponent not ActivityComponent
> Fix Documentation

- compiler/src/main/java/com/squareup/anvil/compiler/codegen/DescriptorUtils.kt
- compiler/src/main/java/com/squareup/anvil/compiler/codegen/dagger/MembersInjectionUtils.kt
- compiler/src/test/java/com/squareup/anvil/compiler/dagger/InjectConstructorFactoryGeneratorTest.kt
- compiler/src/test/java/com/squareup/anvil/compiler/dagger/MembersInjectorGeneratorTest.kt
> fix member injection for supers from a different module

- compiler-utils/src/main/java/com/squareup/anvil/compiler/internal/ClassReference.kt
- compiler/src/main/java/com/squareup/anvil/compiler/codegen/DescriptorUtils.kt
- compiler/src/main/java/com/squareup/anvil/compiler/codegen/KotlinPoetUtils.kt
- compiler/src/main/java/com/squareup/anvil/compiler/codegen/Parameter.kt
- compiler/src/main/java/com/squareup/anvil/compiler/codegen/dagger/MembersInjectionUtils.kt
- compiler/src/main/java/com/squareup/anvil/compiler/codegen/dagger/MembersInjectorGenerator.kt
- compiler/src/test/java/com/squareup/anvil/compiler/dagger/MembersInjectorGeneratorTest.kt
> fix member injection for multiple supers from a different module

- compiler-utils/src/main/java/com/squareup/anvil/compiler/internal/PsiUtils.kt
- compiler/src/test/java/com/squareup/anvil/compiler/dagger/MembersInjectorGeneratorTest.kt
> fix ClassDescriptor resolution for typealias

- compiler-utils/src/main/java/com/squareup/anvil/compiler/internal/PsiUtils.kt
- compiler/src/test/java/com/squareup/anvil/compiler/dagger/MembersInjectorGeneratorTest.kt
> fix PSI resolution of local references to nested types

- compiler-utils/src/main/java/com/squareup/anvil/compiler/internal/ClassReference.kt
- compiler/src/main/java/com/squareup/anvil/compiler/codegen/dagger/MembersInjectionUtils.kt
- compiler/src/main/java/com/squareup/anvil/compiler/codegen/dagger/MembersInjectorGenerator.kt
- compiler/src/test/java/com/squareup/anvil/compiler/dagger/InjectConstructorFactoryGeneratorTest.kt
- compiler/src/test/java/com/squareup/anvil/compiler/dagger/MembersInjectorGeneratorTest.kt
> avoid parsing full class hierarchies for injected members when possible

- compiler-utils/src/main/java/com/squareup/anvil/compiler/internal/PsiUtils.kt
- compiler/src/test/java/com/squareup/anvil/compiler/dagger/InjectConstructorFactoryGeneratorTest.kt
> Resolve inner classes imported by a star import properly.

- annotations/src/main/java/com/squareup/anvil/annotations/ContributesSubcomponent.kt
- compiler-utils/src/main/java/com/squareup/anvil/compiler/internal/ClassReference.kt
- compiler-utils/src/main/java/com/squareup/anvil/compiler/internal/CompilerUtils.kt
- compiler-utils/src/main/java/com/squareup/anvil/compiler/internal/PsiUtils.kt
- compiler/src/main/java/com/squareup/anvil/compiler/codegen/ContributesSubcomponentGenerator.kt
- compiler/src/main/java/com/squareup/anvil/compiler/codegen/ContributesSubcomponentHandlerGenerator.kt
- compiler/src/test/java/com/squareup/anvil/compiler/codegen/ContributesSubcomponentGeneratorTest.kt
- compiler/src/test/java/com/squareup/anvil/compiler/codegen/ContributesSubcomponentHandlerGeneratorTest.kt
> Allow replacing subcomponents

- .github/workflows/ci.yml
- .github/workflows/release.yaml
- CHANGELOG.md
- RELEASING.md
This PR automates publishing SNAPSHOT releases fully and partially automates production releases.
> Automate publishing

- compiler-utils/src/main/java/com/squareup/anvil/compiler/internal/PsiUtils.kt
- compiler/src/test/java/com/squareup/anvil/compiler/codegen/ContributesSubcomponentHandlerGeneratorTest.kt
> Properly parse the `FqName` if the type reference is an inner class.

- compiler/src/main/java/com/squareup/anvil/compiler/codegen/ContributesSubcomponentHandlerGenerator.kt
- compiler/src/test/java/com/squareup/anvil/compiler/codegen/ContributesSubcomponentHandlerGeneratorTest.kt
Before, the code relied on the fact that the trigger was always found before the contributed subcomponent.
Fixes #478
> Generate code for `@ContributedSubcomponent`s when the trigger is created AFTER the contribution. 

- .github/workflows/ci.yml
- .github/workflows/release.yaml
Please only review the 2nd commit.
> Test more AGP versions in CI.

- compiler/generate_build_properties.gradle
- compiler/src/test/java/com/squareup/anvil/compiler/InterfaceMergerTest.kt
- compiler/src/test/java/com/squareup/anvil/compiler/ModuleMergerTest.kt
- compiler/src/test/java/com/squareup/anvil/compiler/TestUtils.kt
- compiler/src/test/java/com/squareup/anvil/compiler/codegen/BindingModuleGeneratorTest.kt
- compiler/src/test/java/com/squareup/anvil/compiler/codegen/BindingModuleMultibindingMapTest.kt
- compiler/src/test/java/com/squareup/anvil/compiler/codegen/BindingModuleMultibindingSetTest.kt
- compiler/src/test/java/com/squareup/anvil/compiler/codegen/BindingModulePriorityTest.kt
- compiler/src/test/java/com/squareup/anvil/compiler/codegen/BindingModuleQualifierTest.kt
- compiler/src/test/java/com/squareup/anvil/compiler/codegen/ContributesSubcomponentHandlerGeneratorTest.kt
- compiler/src/test/java/com/squareup/anvil/compiler/dagger/AssistedFactoryGeneratorTest.kt
- compiler/src/test/java/com/squareup/anvil/compiler/dagger/AssistedInjectGeneratorTest.kt
- compiler/src/test/java/com/squareup/anvil/compiler/dagger/InjectConstructorFactoryGeneratorTest.kt
- compiler/src/test/java/com/squareup/anvil/compiler/dagger/MembersInjectorGeneratorTest.kt
- compiler/src/test/java/com/squareup/anvil/compiler/dagger/ProvidesMethodFactoryGeneratorTest.kt
- dependencies.gradle
This helps me during development.
> Introduce a flag to skip several tests in the :compiler module to improve local development.

- compiler-utils/src/main/java/com/squareup/anvil/compiler/internal/FqName.kt
- compiler-utils/src/main/java/com/squareup/anvil/compiler/internal/KotlinPoetUtils.kt
- compiler-utils/src/main/java/com/squareup/anvil/compiler/internal/reference/AnnotationReference.kt
- compiler-utils/src/main/java/com/squareup/anvil/compiler/internal/reference/ClassReference.kt
- compiler-utils/src/main/java/com/squareup/anvil/compiler/internal/reference/PsiToAnnotationSpecHelper.kt
- compiler/src/main/java/com/squareup/anvil/compiler/codegen/BindingModuleGenerator.kt
- compiler/src/main/java/com/squareup/anvil/compiler/codegen/ContributedBinding.kt
- compiler/src/main/java/com/squareup/anvil/compiler/codegen/ContributesSubcomponentHandlerGenerator.kt
- compiler/src/main/java/com/squareup/anvil/compiler/codegen/DescriptorUtils.kt
- compiler/src/main/java/com/squareup/anvil/compiler/codegen/KotlinPoetUtils.kt
- compiler/src/main/java/com/squareup/anvil/compiler/codegen/PsiUtils.kt
I recommend reviewing this PR commit by commit. I have more changes in a follow-up PR based on this one.
> Extract more utilities for `ClassReference`

- compiler/src/test/java/com/squareup/anvil/compiler/codegen/ContributesMultibindingGeneratorTest.kt
Now that we use `ClassReference` everywhere, these tests no longer fail.
> Add test cases for #477

- compiler/src/main/java/com/squareup/anvil/compiler/ClassScannerIr.kt
- compiler/src/main/java/com/squareup/anvil/compiler/IrUtils.kt
- compiler/src/main/java/com/squareup/anvil/compiler/ModuleMergerIr.kt
- compiler/src/main/java/com/squareup/anvil/compiler/codegen/reference/AnnotationReferenceIr.kt
- compiler/src/main/java/com/squareup/anvil/compiler/codegen/reference/ClassReferenceIr.kt
There are a couple spots with TODOs added but this completes the migration for the most part.
> Migrate the remainder of `ModuleMergerIr` to use Reference classes

- compiler-utils/src/main/java/com/squareup/anvil/compiler/internal/reference/TypeReference.kt
- compiler/src/test/java/com/squareup/anvil/compiler/dagger/ProvidesMethodFactoryGeneratorTest.kt
> Fix detection of generic types for automatically adding `@JvmSuppressWildcards`

- annotations/src/main/java/com/squareup/anvil/annotations/ContributesBinding.kt
- annotations/src/main/java/com/squareup/anvil/annotations/ContributesMultibinding.kt
- compiler/src/main/java/com/squareup/anvil/compiler/codegen/BindingModuleGenerator.kt
- compiler/src/main/java/com/squareup/anvil/compiler/codegen/ContributesBindingGenerator.kt
- compiler/src/main/java/com/squareup/anvil/compiler/codegen/ContributesMultibindingGenerator.kt
- compiler/src/test/java/com/squareup/anvil/compiler/codegen/BindingModuleGeneratorTest.kt
- compiler/src/test/java/com/squareup/anvil/compiler/codegen/BindingModuleMultibindingSetTest.kt
- compiler/src/test/java/com/squareup/anvil/compiler/codegen/BindingModulePriorityTest.kt
- compiler/src/test/java/com/squareup/anvil/compiler/codegen/BindingModuleQualifierTest.kt
- compiler/src/test/java/com/squareup/anvil/compiler/codegen/ContributesBindingGeneratorTest.kt
- compiler/src/test/java/com/squareup/anvil/compiler/codegen/ContributesMultibindingGeneratorTest.kt
The size of the PR looks scary. But guess what, that's only tests. There are minimal changes in the plugin itself (just +10 lines of code in fact).
> Make `@ContributesBinding` and `@ContributesMultibinding` repeatable.

- compiler/src/main/java/com/squareup/anvil/compiler/ClassScanner.kt
I benchmarked it and measured a 5-10% improvement.
> Cache the results when scanning contributed hints.

- compiler-api/README.md
> Update the documentation for custom code generators.

- compiler-utils/src/main/java/com/squareup/anvil/compiler/internal/reference/TypeReference.kt
- compiler/src/test/java/com/squareup/anvil/compiler/dagger/AssistedFactoryGeneratorTest.kt
> Preserve nullability when converting lambdas to function types

- compiler-utils/src/main/java/com/squareup/anvil/compiler/internal/PsiUtils.kt
- compiler-utils/src/main/java/com/squareup/anvil/compiler/internal/reference/AnnotationArgumentReference.kt
- compiler/src/test/java/com/squareup/anvil/compiler/internal/reference/AnnotationReferenceTest.kt
> Support wildcard imports for constant when resolving annotation arguments

- compiler-utils/src/main/java/com/squareup/anvil/compiler/internal/PsiUtils.kt
- compiler/src/test/java/com/squareup/anvil/compiler/internal/reference/ClassReferenceTest.kt
> Avoid a stackoverflow when querying all super types.

- compiler-utils/src/main/java/com/squareup/anvil/compiler/internal/reference/TypeReference.kt
- compiler/src/main/java/com/squareup/anvil/compiler/codegen/dagger/DaggerGenerationUtils.kt
- compiler/src/main/java/com/squareup/anvil/compiler/codegen/dagger/MembersInjectorGenerator.kt
- compiler/src/main/java/com/squareup/anvil/compiler/codegen/dagger/Parameter.kt
- compiler/src/test/java/com/squareup/anvil/compiler/dagger/MembersInjectorGeneratorTest.kt
> Fix dagger factory member injection not handling generics.

- compiler/src/main/java/com/squareup/anvil/compiler/codegen/AnnotationReferenceExtensions.kt
- compiler/src/main/java/com/squareup/anvil/compiler/codegen/BindingModuleGenerator.kt
- compiler/src/test/java/com/squareup/anvil/compiler/codegen/BindingModuleGeneratorTest.kt
> Correctly merge bindings from all scopes, if multiple `@Merge*` annotations are used

- CHANGELOG.md
- compiler-utils/src/main/java/com/squareup/anvil/compiler/internal/KotlinPoetUtils.kt
- dependencies.gradle
> Upgrade KotlinPoet to the latest version.

- compiler-utils/src/main/java/com/squareup/anvil/compiler/internal/FqName.kt
- compiler-utils/src/main/java/com/squareup/anvil/compiler/internal/reference/TypeReference.kt
- compiler/src/test/java/com/squareup/anvil/compiler/internal/reference/TypeReferenceTest.kt
> Support star projections for wrapped type references.

- compiler/src/main/java/com/squareup/anvil/compiler/Utils.kt
- compiler/src/main/java/com/squareup/anvil/compiler/codegen/ClassReferenceExtensions.kt
- compiler/src/test/java/com/squareup/anvil/compiler/codegen/ContributesBindingGeneratorTest.kt
- compiler/src/test/java/com/squareup/anvil/compiler/codegen/ContributesMultibindingGeneratorTest.kt
> Support contributing types with `Any` as `boundType`.

- compiler-utils/src/main/java/com/squareup/anvil/compiler/internal/reference/AnvilModuleDescriptor.kt
- compiler-utils/src/main/java/com/squareup/anvil/compiler/internal/reference/TypeReference.kt
- compiler/src/main/java/com/squareup/anvil/compiler/codegen/reference/RealAnvilModuleDescriptor.kt
- compiler/src/test/java/com/squareup/anvil/compiler/dagger/MembersInjectorGeneratorTest.kt
- compiler/src/test/java/com/squareup/anvil/compiler/internal/reference/TypeReferenceTest.kt
> Unwrap types from type aliases for `TypeReference`.

- compiler-utils/src/main/java/com/squareup/anvil/compiler/internal/reference/AnnotationArgumentReference.kt
- compiler/src/test/java/com/squareup/anvil/compiler/internal/reference/AnnotationReferenceTest.kt
> Fix annotation arguments using string templates not being parsed correctly

- compiler-utils/src/main/java/com/squareup/anvil/compiler/internal/reference/PropertyReference.kt
- compiler/src/main/java/com/squareup/anvil/compiler/Utils.kt
- compiler/src/main/java/com/squareup/anvil/compiler/codegen/dagger/DaggerGenerationUtils.kt
- compiler/src/test/java/com/squareup/anvil/compiler/dagger/MembersInjectorGeneratorTest.kt
> Align Anvil with Dagger and don't support member injection for private fields

- compiler-utils/src/main/java/com/squareup/anvil/compiler/internal/PsiUtils.kt
- compiler/src/test/java/com/squareup/anvil/compiler/codegen/BindingModuleGeneratorTest.kt
- compiler/src/test/java/com/squareup/anvil/compiler/internal/reference/AnnotationReferenceTest.kt
- compiler/src/test/java/com/squareup/anvil/compiler/internal/reference/PropertyReferenceTest.kt
- compiler/src/test/java/com/squareup/anvil/compiler/internal/reference/TypeReferenceTest.kt
> Strip out backticks from type names before attempting type resolution

- compiler/src/main/java/com/squareup/anvil/compiler/Utils.kt
- compiler/src/main/java/com/squareup/anvil/compiler/codegen/dagger/BindsMethodValidator.kt
- compiler/src/main/java/com/squareup/anvil/compiler/codegen/dagger/DaggerGenerationUtils.kt
- compiler/src/main/java/com/squareup/anvil/compiler/codegen/dagger/ProvidesMethodFactoryGenerator.kt
- compiler/src/test/java/com/squareup/anvil/compiler/dagger/BindsMethodValidatorTest.kt
> Validate @Binds methods when generating dagger factories

- compiler-utils/build.gradle
- compiler-utils/src/main/java/com/squareup/anvil/compiler/internal/reference/ClassReference.kt
- compiler-utils/src/testFixtures/java/com/squareup/anvil/compiler/internal/testing/AnvilCompilation.kt
- compiler/src/main/java/com/squareup/anvil/compiler/codegen/dagger/MapKeyCreatorGenerator.kt
- compiler/src/test/java/com/squareup/anvil/compiler/dagger/MapKeyCreatorGeneratorTest.kt
- compiler/src/test/java/com/squareup/anvil/compiler/dagger/TestClasses.kt
- dependencies.gradle
> Generate MapKey creators

- compiler/src/main/java/com/squareup/anvil/compiler/codegen/dagger/BindsMethodValidator.kt
- compiler/src/test/java/com/squareup/anvil/compiler/dagger/BindsMethodValidatorTest.kt
> Handle extension functions when validating @Binds methods with generateDaggerFactories

- .github/workflows/ci.yml
- .github/workflows/release.yaml
- CHANGELOG.md
- build.gradle
- compiler-utils/build.gradle
- compiler-utils/src/testFixtures/java/com/squareup/anvil/compiler/internal/testing/AnvilCompilation.kt
- compiler-utils/src/testFixtures/preview/com/squareup/anvil/compiler/internal/testing/KotlinCompilationExtensions.kt
- compiler-utils/src/testFixtures/stable/com/squareup/anvil/compiler/internal/testing/KotlinCompilationExtensions.kt
- compiler/build.gradle
- compiler/src/test/java/com/squareup/anvil/compiler/InterfaceMergerTest.kt
- compiler/src/test/java/com/squareup/anvil/compiler/MergeModulesTest.kt
- compiler/src/test/java/com/squareup/anvil/compiler/ModuleMergerTest.kt
- compiler/src/test/java/com/squareup/anvil/compiler/codegen/BindingModuleGeneratorTest.kt
- compiler/src/test/java/com/squareup/anvil/compiler/codegen/BindingModuleMultibindingSetTest.kt
- compiler/src/test/java/com/squareup/anvil/compiler/codegen/ContributesBindingGeneratorTest.kt
- compiler/src/test/java/com/squareup/anvil/compiler/codegen/ContributesMultibindingGeneratorTest.kt
- compiler/src/test/java/com/squareup/anvil/compiler/codegen/ContributesSubcomponentGeneratorTest.kt
- compiler/src/test/java/com/squareup/anvil/compiler/codegen/ContributesToGeneratorTest.kt
- compiler/src/test/java/com/squareup/anvil/compiler/dagger/AnvilAnnotationDetectorCheckTest.kt
- compiler/src/test/java/com/squareup/anvil/compiler/dagger/AnvilMergeAnnotationDetectorCheckTest.kt
- compiler/src/test/java/com/squareup/anvil/compiler/dagger/ComponentDetectorCheckTest.kt
- compiler/src/test/java/com/squareup/anvil/compiler/dagger/ProvidesMethodFactoryGeneratorTest.kt
- dependencies.gradle
- gradle-plugin/build.gradle
- gradle.properties
- integration-tests/code-generator/build.gradle
Upgrade Anvil to Kotlin 1.8 and stop supporting 1.7 moving forward.
> Kotlin 1.8

- CHANGELOG.md
- compiler-utils/src/main/java/com/squareup/anvil/compiler/internal/reference/AnvilModuleDescriptor.kt
- compiler-utils/src/main/java/com/squareup/anvil/compiler/internal/reference/ClassReference.kt
- compiler-utils/src/main/java/com/squareup/anvil/compiler/internal/reference/FunctionReference.kt
- compiler-utils/src/main/java/com/squareup/anvil/compiler/internal/reference/FunctionalReference.kt
- compiler-utils/src/main/java/com/squareup/anvil/compiler/internal/reference/ParameterReference.kt
- compiler-utils/src/main/java/com/squareup/anvil/compiler/internal/reference/PropertyReference.kt
- compiler-utils/src/main/java/com/squareup/anvil/compiler/internal/reference/TopLevelFunctionReference.kt
- compiler-utils/src/main/java/com/squareup/anvil/compiler/internal/reference/TopLevelPropertyReference.kt
- compiler-utils/src/main/java/com/squareup/anvil/compiler/internal/reference/TypeParameterReference.kt
- compiler-utils/src/main/java/com/squareup/anvil/compiler/internal/reference/TypeReference.kt
- compiler-utils/src/main/java/com/squareup/anvil/compiler/internal/reference/VariableReference.kt
- compiler/src/main/java/com/squareup/anvil/compiler/codegen/dagger/AssistedFactoryGenerator.kt
- compiler/src/main/java/com/squareup/anvil/compiler/codegen/dagger/BindsMethodValidator.kt
- compiler/src/main/java/com/squareup/anvil/compiler/codegen/dagger/DaggerGenerationUtils.kt
- compiler/src/main/java/com/squareup/anvil/compiler/codegen/dagger/ProvidesMethodFactoryGenerator.kt
- compiler/src/main/java/com/squareup/anvil/compiler/codegen/reference/RealAnvilModuleDescriptor.kt
- compiler/src/test/java/com/squareup/anvil/compiler/internal/reference/TopLevelFunctionReferenceTest.kt
- compiler/src/test/java/com/squareup/anvil/compiler/internal/reference/TopLevelPropertyReferenceTest.kt
- integration-tests/code-generator-tests/src/main/java/com/squareup/anvil/test/Trigger.kt
- integration-tests/code-generator-tests/src/test/java/com/squareup/anvil/test/GeneratedCodeTest.kt
- integration-tests/code-generator/src/main/java/com/squareup/anvil/test/TestCodeGenerator.kt
> Allow querying top-level functions and properties

- compiler/src/main/java/com/squareup/anvil/compiler/codegen/BindingModuleGenerator.kt
- compiler/src/main/java/com/squareup/anvil/compiler/codegen/ContributedBinding.kt
- compiler/src/test/java/com/squareup/anvil/compiler/codegen/ContributesBindingGeneratorTest.kt
Fixes https://github.com/square/anvil/issues/680
> Support contributing types with Any as boundType

- compiler-utils/src/main/java/com/squareup/anvil/compiler/internal/reference/TypeReference.kt
- compiler/src/test/java/com/squareup/anvil/compiler/dagger/AssistedFactoryGeneratorTest.kt
- compiler/src/test/java/com/squareup/anvil/compiler/dagger/AssistedInjectGeneratorTest.kt
Fixes #745.
This use-case primarily popped up with assisted parameter and factory generation. We would get an error like: e: Class 'AssistedServiceFactory_Impl' is not abstract and does not implement abstract member public abstract fun create(stringFactory: suspend (Int) -> String): AssistedService defined in com.squareup.test.AssistedServiceFactory e: AssistedServiceFactory_Impl.kt:25:3 'create' overrides nothing
This is because we manually override the generated code for lambdas to address differences between Psi and Descriptors. There is a possibility that we could continue overriding the default generated code for suspend lambdas with modifications to what we currently do, but I found doing so to introduce problematic casting requirements that would spread beyond this isolated area of …
> Fix suspend lambdas not being supported

- compiler/src/main/java/com/squareup/anvil/compiler/codegen/dagger/MapKeyCreatorGenerator.kt
- compiler/src/main/java/com/squareup/anvil/compiler/codegen/ksp/KspUtil.kt
- compiler/src/test/java/com/squareup/anvil/compiler/dagger/MapKeyCreatorGeneratorTest.kt
> Support KSP in MapKeyCreatorGenerator

- .github/workflows/ci.yml
- annotations-optional/dependencies/runtimeClasspath.txt
- annotations/dependencies/runtimeClasspath.txt
- build-logic/conventions/build.gradle
- build-logic/conventions/src/main/kotlin/com/squareup/anvil/conventions/LibraryPlugin.kt
- compiler-api/dependencies/runtimeClasspath.txt
- compiler-utils/dependencies/runtimeClasspath.txt
- compiler/dependencies/runtimeClasspath.txt
- gradle-plugin/dependencies/runtimeClasspath.txt
- gradle/libs.versions.toml
https://github.com/dropbox/dependency-guard
> introduce the dependency-guard plugin

- .github/workflows/ci.yml
- annotations-optional/dependencies/runtimeClasspath.txt
- annotations/dependencies/runtimeClasspath.txt
- build-logic/settings/src/main/kotlin/com/squareup/anvil/builds/settings/SettingsPlugin.kt
- compiler-api/dependencies/runtimeClasspath.txt
- compiler-utils/dependencies/runtimeClasspath.txt
- compiler/dependencies/runtimeClasspath.txt
- gradle-plugin/dependencies/runtimeClasspath.txt
- gradle/libs.versions.toml
Giving the 1.9.20 versions a try while https://github.com/google/ksp/issues/1653 and https://github.com/square/anvil/pull/814 are in flux
> Upgrade to Kotlin 1.9.20

- compiler/src/main/java/com/squareup/anvil/compiler/codegen/CodeGenerationExtension.kt
- gradle-plugin/src/gradleTest/java/com/squareup/anvil/plugin/IncrementalTest.kt
> Add restored-from-cache, previously-generated files to analysis results after code generation

- compiler/api/compiler.api
- compiler/src/main/java/com/squareup/anvil/compiler/AnvilComponentRegistrar.kt
Resolves #912. Should merge after #901, #907, #899, and #877 are in
> Support K2 in AnvilComponentRegistrar

- compiler/src/main/java/com/squareup/anvil/compiler/codegen/ksp/KSAnnotationExtensions.kt
- compiler/src/test/java/com/squareup/anvil/compiler/TestUtils.kt
- compiler/src/test/java/com/squareup/anvil/compiler/codegen/ContributesBindingGeneratorTest.kt
Idk why I thought this showed up as a `KSName` in KSP 😅
> Fix KSP resolution of Priority

- gradle-plugin/src/main/java/com/squareup/anvil/plugin/AnvilExtension.kt
This fixes gradle compat with the K2 KGP plugin
> Fix private targets API use

- compiler/src/test/java/com/squareup/anvil/compiler/codegen/incremental/CacheTestEnvironment.kt
Leftover from here: https://github.com/square/anvil/pull/979#discussion_r1578596878
> delete leftover unused test function

- gradle/libs.versions.toml
- Enables us to continue publishing snapshots (#1139)
> Update mavenPublish to v0.33.0
