.github/workflows/ci.yml
Pass the Kotlin version as parameter to Gradle to run the build with the desired version in CI.
=> Pass the Kotlin version as parameter to Gradle 

gradle-plugin/src/main/java/com/squareup/hephaestus/plugin/HephaestusPlugin.kt, sample/app/build.gradle, settings.gradle
Gradle's `PluginManager.withPlugin(...)` API covers this case, and avoids the need for ordering issues in most cases. Fixes #8
=> Fix plugin ordering requirements

.github/workflows/ci.yml, build.gradle, gradle-plugin/build.gradle
These CI runs are optional and don't prevent a merge.
=> Run a build in CI with a Kotlin dev build. 

compiler/build.gradle, compiler/src/test/java/com/squareup/hephaestus/compiler/ContributesToGeneratorTest.kt, compiler/src/test/java/com/squareup/hephaestus/compiler/TestUtils.kt, gradle-plugin/build.gradle, gradle-plugin/src/main/java/com/squareup/hephaestus/plugin/CheckMixedSourceSet.kt, gradle-plugin/src/main/java/com/squareup/hephaestus/plugin/HephaestusPlugin.kt, sample/library/build.gradle
Use @OptIn(ExperimentalStdlibApi::class) instead of @ExperimentalStdlibApi to avoid for consumers of the Gradle plugin to add a flag to the Kotlin compiler.
=> Use @OptIn(ExperimentalStdlibApi::class) instead of @ExperimentalStdlibApi

compiler/src/main/java/com/squareup/hephaestus/compiler/ClassScanner.kt, compiler/src/main/java/com/squareup/hephaestus/compiler/ContributeToGenerator.kt, compiler/src/main/java/com/squareup/hephaestus/compiler/HephaestusCommandLineProcessor.kt, compiler/src/main/java/com/squareup/hephaestus/compiler/HephaestusComponentRegistrar.kt, compiler/src/main/java/com/squareup/hephaestus/compiler/InterfaceMerger.kt, compiler/src/main/java/com/squareup/hephaestus/compiler/ModuleMerger.kt, compiler/src/main/java/com/squareup/hephaestus/compiler/Utils.kt, compiler/src/test/java/com/squareup/hephaestus/compiler/ContributesToGeneratorTest.kt, compiler/src/test/java/com/squareup/hephaestus/compiler/InterfaceMergerTest.kt, compiler/src/test/java/com/squareup/hephaestus/compiler/MergeModulesTest.kt, compiler/src/test/java/com/squareup/hephaestus/compiler/ModuleMergerTest.kt, compiler/src/test/java/com/squareup/hephaestus/compiler/TestUtils.kt, sample/app/src/main/java/com/squareup/hephaestus/sample/RandomModule.kt, sample/app/src/test/java/com/squareup/hephaestus/sample/RandomModuleTest.kt
This change removes some workarounds for discovering contributed classes in the same module as components are merged. It also allows implementing other features that require more code generating in the future.
=> Allow generating code in all Kotlin compile tasks

gradle-plugin/src/main/java/com/squareup/hephaestus/plugin/DisableIncrementalCompilationTask.kt, gradle-plugin/src/main/java/com/squareup/hephaestus/plugin/HephaestusPlugin.kt, gradle-plugin/src/main/java/com/squareup/hephaestus/plugin/IncrementalSignal.kt, gradle.properties
Using versions: [Kotlin:1.4-M3, Gradle:6.5, AGP 4.1 beta 04], I could detect some issues when running instant execution: 
```
428 problems were found reusing the configuration cache, 4 of which seem unique.
- field '$disableIncrementalCompilationTaskProvider' from type 'com.squareup.hephaestus.plugin.HephaestusPlugin$disableIncrementalKotlinCompilation$disableIncrementalCompilationAction$1$1': cannot deserialize object of type 'org.gradle.api.Task' as these are not supported with the configuration cache.
See https://docs.gradle.org/6.6-rc-1/userguide/configuration_cache.html#config_cache:requirements:task_access
- field '$disableIncrementalCompilationTaskProvider' from type 'com.squareup.hephaestus.plugin.HephaestusPlugin$disableIncrementalKotlinCompilation$disableIncrementalCompilationAct …
```
=> Fixes Configuration caching issues

build.gradle, gradle-plugin/build.gradle
Avoid relying on the currently configured JDK.
=> Set an explicit target and source Java version

CHANGELOG.md, compiler/src/main/java/com/squareup/hephaestus/compiler/InterfaceMerger.kt, compiler/src/main/java/com/squareup/hephaestus/compiler/ModuleMerger.kt, compiler/src/test/java/com/squareup/hephaestus/compiler/InterfaceMergerTest.kt, compiler/src/test/java/com/squareup/hephaestus/compiler/MergeModulesTest.kt, compiler/src/test/java/com/squareup/hephaestus/compiler/ModuleMergerTest.kt
Ensure that types cannot be included and excluded at the same time, which leads to unexpected results.
=> Disallow including and excluding types at the same time.

gradle-plugin/src/main/java/com/squareup/hephaestus/plugin/DisableIncrementalCompilationTask.kt, gradle-plugin/src/main/java/com/squareup/hephaestus/plugin/HephaestusPlugin.kt, gradle-plugin/src/main/java/com/squareup/hephaestus/plugin/IncrementalSignal.kt
This fixes an issue since, if using modern plugin syntax, plugins run in
their own class loader, meaning that the same class can't be used across
projects. This breaks the incremental signal up per project, using a 
WorkerServiceRegistry so that it can be accessed by multiple tasks
within a project.
I suspect that the issue revealed in #31 is related to Gradle's [classloader isolation](https://docs.gradle.org/current/javadoc/org/gradle/workers/WorkerExecutor.html#classLoaderIsolation-org.gradle.api.Action-).  The fact that it works if you add the plugin as a classpath dependency in the buildscript, but doesn't if you add it using modern plugin syntax suggests that to be the case.
I believe that since the plugin is attempting to access the incremental signal from the `KotlinCompile` task, …
=> Introduces a service registry for the incrementalSignal service.

CHANGELOG.md, gradle-plugin/src/main/java/com/squareup/anvil/plugin/AnvilPlugin.kt
This prevents misleading results where one could forget to apply the Gradle
plugin. Imagine module B depends on module A. A applies the Gradle plugin, which
adds an `api` dependency for the annotation. In module B you can reference
the annotations due the transitive dependency, but the compiler plugin won't
run, because the Gradle plugin wasn't applied in this module. By using an
`implementation` dependency you cannot reference the annotations in module B
without applying the Gradle plugin.
Fixes #40
=> Add the annotation artifact as an `implementation` dependency instead of `api`.

CHANGELOG.md, gradle-plugin/src/main/java/com/squareup/anvil/plugin/AnvilPlugin.kt, gradle-plugin/src/main/java/com/squareup/anvil/plugin/DisableIncrementalCompilationTask.kt, gradle-plugin/src/main/java/com/squareup/anvil/plugin/IncrementalSignal.kt
This PR reverts #35, which accidentally added a hard dependency on the Android Gradle Plugin. It fixes #31 in a different way and resolves #39 due to the revert.
=> Allow the plugin to be used in pure JVM modules

compiler/src/main/java/com/squareup/anvil/compiler/AnvilCompilationException.kt, compiler/src/main/java/com/squareup/anvil/compiler/AnvilComponentRegistrar.kt, compiler/src/main/java/com/squareup/anvil/compiler/ClassScanner.kt, compiler/src/main/java/com/squareup/anvil/compiler/InterfaceMerger.kt, compiler/src/main/java/com/squareup/anvil/compiler/ModuleMerger.kt, compiler/src/main/java/com/squareup/anvil/compiler/Utils.kt, compiler/src/main/java/com/squareup/anvil/compiler/codegen/BindingModuleGenerator.kt, compiler/src/main/java/com/squareup/anvil/compiler/codegen/ContributesBindingGenerator.kt, compiler/src/main/java/com/squareup/anvil/compiler/codegen/ContributesToGenerator.kt, compiler/src/test/java/com/squareup/anvil/compiler/MergeModulesTest.kt, compiler/src/test/java/com/squareup/anvil/compiler/ModuleMergerTest.kt, compiler/src/test/java/com/squareup/anvil/compiler/TestUtils.kt, compiler/src/test/java/com/squareup/anvil/compiler/codegen/BindingModuleGeneratorTest.kt, integration-tests/tests/src/test/java/com/squareup/anvil/test/MergeComponentTest.kt, integration-tests/tests/src/test/java/com/squareup/anvil/test/MergeModulesTest.kt, integration-tests/tests/src/test/java/com/squareup/anvil/test/Utils.kt
This PR depends on #48 and actually implements some parts in order to make to `@ContributesBinding` work. The bounded type is still required and replacements and exclusions don't work, yet.
=> Generate an Anvil Dagger module with contributed bindings

compiler/src/main/java/com/squareup/anvil/compiler/AnvilComponentRegistrar.kt, compiler/src/main/java/com/squareup/anvil/compiler/ModuleMerger.kt, compiler/src/main/java/com/squareup/anvil/compiler/codegen/BindingModuleGenerator.kt, compiler/src/test/java/com/squareup/anvil/compiler/InterfaceMergerTest.kt, compiler/src/test/java/com/squareup/anvil/compiler/MergeModulesTest.kt, compiler/src/test/java/com/squareup/anvil/compiler/ModuleMergerTest.kt, compiler/src/test/java/com/squareup/anvil/compiler/TestUtils.kt, compiler/src/test/java/com/squareup/anvil/compiler/codegen/BindingModuleGeneratorTest.kt
This is the last PR for the contributing binding feature. It implements the various exclusion and replacement rules.
=> Implement exclusion and replacements for contributed bindings

README.md, annotations/src/main/java/com/squareup/anvil/annotations/ContributesBinding.kt, annotations/src/main/java/com/squareup/anvil/annotations/ContributesTo.kt, compiler/src/main/java/com/squareup/anvil/compiler/InterfaceMerger.kt, compiler/src/main/java/com/squareup/anvil/compiler/ModuleMerger.kt, compiler/src/main/java/com/squareup/anvil/compiler/Utils.kt, compiler/src/main/java/com/squareup/anvil/compiler/codegen/BindingModuleGenerator.kt, compiler/src/test/java/com/squareup/anvil/compiler/InterfaceMergerTest.kt, compiler/src/test/java/com/squareup/anvil/compiler/MergeModulesTest.kt, compiler/src/test/java/com/squareup/anvil/compiler/ModuleMergerTest.kt, compiler/src/test/java/com/squareup/anvil/compiler/codegen/BindingModuleGeneratorTest.kt, sample/app/src/androidTest/java/com/squareup/anvil/sample/FakeFatherProviderModule.kt
This gives the API more flexibility and avoids redundant classes. E.g. one Dagger module with several binding and provider methods may wish to replace multiple other Dagger modules.
=> Change the `replaces` attribute from a single class to an array. 

compiler/src/main/java/com/squareup/anvil/compiler/ClassScanner.kt, compiler/src/main/java/com/squareup/anvil/compiler/InterfaceMerger.kt, compiler/src/main/java/com/squareup/anvil/compiler/ModuleMerger.kt, compiler/src/main/java/com/squareup/anvil/compiler/Utils.kt, compiler/src/main/java/com/squareup/anvil/compiler/codegen/BindingModuleGenerator.kt, compiler/src/main/java/com/squareup/anvil/compiler/codegen/ContributesBindingGenerator.kt, compiler/src/main/java/com/squareup/anvil/compiler/codegen/ContributesToGenerator.kt, compiler/src/main/java/com/squareup/anvil/compiler/codegen/PsiUtils.kt, compiler/src/test/java/com/squareup/anvil/compiler/InterfaceMergerTest.kt, compiler/src/test/java/com/squareup/anvil/compiler/ModuleMergerTest.kt, compiler/src/test/java/com/squareup/anvil/compiler/TestUtils.kt, compiler/src/test/java/com/squareup/anvil/compiler/codegen/ContributesBindingGeneratorTest.kt, compiler/src/test/java/com/squareup/anvil/compiler/codegen/ContributesToGeneratorTest.kt, gradle.properties
This PR fixes #45. It requires quite a lot of changes. 
The hint for the scope allows us to filter classes without resolving them. Resolving classes can be problematic, because super types need to be resolved and we modify the super types for certain classes. This would result in never ending recursive loop inside of the compiler.
This PR depends on #54, which requires a major version bump according to semantic versioning. This also allows to make non-backwards compatible changes here. Users don't need to fix any code, they only must recompile all libraries using Anvil at the same time. In a monorepo this isn't a concern.
=> Generate a hint for the scope of each contributed type.

compiler/src/main/java/com/squareup/anvil/compiler/codegen/BindingModuleGenerator.kt, compiler/src/test/java/com/squareup/anvil/compiler/codegen/BindingModuleGeneratorTest.kt
This is an example of a (more complicated) error for `ParentInterface<Map<String, List<Pair<String, Int>>>, SomeOtherType>`
>  com.squareup.anvil.compiler.AnvilCompilationException: Back-end (JVM) Internal error: Binding com.squareup.test.ParentInterface contains type parameters(s) <Map<String, List<Pair<String, Int>>>, SomeOtherType>. Type parameters in bindings are not supported. This binding needs to be contributed to a dagger module manually
=> Throw a compilation error when the contributed binding has a type argument.

.github/workflows/ci.yml, compiler/build.gradle, compiler/src/main/java/com/squareup/anvil/compiler/AnvilCommandLineProcessor.kt, compiler/src/main/java/com/squareup/anvil/compiler/AnvilComponentRegistrar.kt, compiler/src/main/java/com/squareup/anvil/compiler/Utils.kt, compiler/src/main/java/com/squareup/anvil/compiler/codegen/BindingModuleGenerator.kt, compiler/src/main/java/com/squareup/anvil/compiler/codegen/PsiUtils.kt, compiler/src/main/java/com/squareup/anvil/compiler/codegen/dagger/ComponentDetectorCheck.kt, compiler/src/main/java/com/squareup/anvil/compiler/codegen/dagger/InjectConstructorFactoryGenerator.kt, compiler/src/main/java/com/squareup/anvil/compiler/codegen/dagger/KotlinPoet.kt, compiler/src/main/java/com/squareup/anvil/compiler/codegen/dagger/MembersInjectorGenerator.kt, compiler/src/main/java/com/squareup/anvil/compiler/codegen/dagger/ProvidesMethodFactoryGenerator.kt, compiler/src/test/java/com/squareup/anvil/compiler/ReflectionUtils.kt, compiler/src/test/java/com/squareup/anvil/compiler/TestUtils.kt, compiler/src/test/java/com/squareup/anvil/compiler/dagger/ComponentDetectorCheckTest.kt, compiler/src/test/java/com/squareup/anvil/compiler/dagger/Factory.kt, compiler/src/test/java/com/squareup/anvil/compiler/dagger/InjectConstructorFactoryGeneratorTest.kt, compiler/src/test/java/com/squareup/anvil/compiler/dagger/MembersInjectorGeneratorTest.kt, compiler/src/test/java/com/squareup/anvil/compiler/dagger/ProvidesMethodFactoryGeneratorTest.kt, dependencies.gradle, gradle-plugin/src/main/java/com/squareup/anvil/plugin/AnvilExtension.kt, gradle-plugin/src/main/java/com/squareup/anvil/plugin/AnvilPlugin.kt, gradle-plugin/src/main/java/com/squareup/anvil/plugin/AnvilSubplugin.kt, integration-tests/library/build.gradle, sample/library/build.gradle
The code that Dagger generates for modules, field injection and inject constructors is trivial. The real magic happens when Dagger compiles components or subcomponents.
This PR gives us the option to use Anvil instead of the Dagger annotation processor to generate the factories that Dagger would generate. This improves build times for many modules. 
These numbers are from our code base when building one of the tiniest development apps:
  | Stub generation | Kapt | Javac | Kotlinc | Sum
--- | --- | --- | --- | --- | ---
With Dagger | 12.976 | 40.377 | 8.571 | 10.241 | 72.165
Anvil | 0 | 0 | 6.965 | 17.748 | 24.713
Notice that many tasks don't exist anymore with this optimization. Since no annotation processor needs to run Kapt stub generation and Kapt itself are gone. Anvil generates …
=> Generate Dagger Factories

compiler/src/main/java/com/squareup/anvil/compiler/codegen/dagger/ComponentDetectorCheck.kt, compiler/src/test/java/com/squareup/anvil/compiler/dagger/ComponentDetectorCheckTest.kt
This is fine, because Dagger only generates the code for Subcomponents when generating the parent Component.
Fixes #74.
=> Allow using Anvil to generate Dagger factories even though the module uses a Subcomponent.

compiler/src/main/java/com/squareup/anvil/compiler/InterfaceMerger.kt, compiler/src/main/java/com/squareup/anvil/compiler/Utils.kt, compiler/src/main/java/com/squareup/anvil/compiler/codegen/KotlinPoet.kt, compiler/src/main/java/com/squareup/anvil/compiler/codegen/PsiUtils.kt, compiler/src/test/java/com/squareup/anvil/compiler/dagger/InjectConstructorFactoryGeneratorTest.kt
Add missing import for inject constructor factories when an injected type is an inner class of the class itself or are parent type.
Fixes #79.
=> Add missing import

compiler/src/main/java/com/squareup/anvil/compiler/codegen/BindingModuleGenerator.kt, compiler/src/main/java/com/squareup/anvil/compiler/codegen/CodeGenerationExtension.kt, compiler/src/main/java/com/squareup/anvil/compiler/codegen/CodeGenerator.kt, compiler/src/main/java/com/squareup/anvil/compiler/codegen/PrivateCodeGenerator.kt, compiler/src/main/java/com/squareup/anvil/compiler/codegen/dagger/ComponentDetectorCheck.kt, compiler/src/main/java/com/squareup/anvil/compiler/codegen/dagger/InjectConstructorFactoryGenerator.kt, compiler/src/main/java/com/squareup/anvil/compiler/codegen/dagger/MembersInjectorGenerator.kt, compiler/src/main/java/com/squareup/anvil/compiler/codegen/dagger/ProvidesMethodFactoryGenerator.kt, compiler/src/test/java/com/squareup/anvil/compiler/dagger/ProvidesMethodFactoryGeneratorTest.kt
Generate a Dagger factory for provider methods that Anvil generates in its Anvil specific modules when the experimental feature is enabled to generate Dagger factories.
=> Missing Factory class

gradle-plugin/gradle/wrapper/gradle-wrapper.properties, gradle-plugin/src/main/java/com/squareup/anvil/plugin/AnvilSubplugin.kt, gradle/wrapper/gradle-wrapper.properties
=> Fix the absolute paths as inputs for Kapt and Kotlin compile tasks.

compiler/src/main/java/com/squareup/anvil/compiler/codegen/KotlinPoet.kt, compiler/src/test/java/com/squareup/anvil/compiler/dagger/InjectConstructorFactoryGeneratorTest.kt
Support inner classes starting with a lowercase character when generating factories for inject constructors.
Fixes #96
=> Fix crash for inner classes starting with a lowercase character

compiler/src/main/java/com/squareup/anvil/compiler/codegen/dagger/ProvidesMethodFactoryGenerator.kt, compiler/src/test/java/com/squareup/anvil/compiler/dagger/ProvidesMethodFactoryGeneratorTest.kt
Throw an error if provider method names clash and Anvil is supposed to generate Dagger factories. Dagger throws the same error.
Fixes #99
=> Throw an error if provider method names clash

compiler/src/main/java/com/squareup/anvil/compiler/codegen/BindingModuleGenerator.kt, compiler/src/main/java/com/squareup/anvil/compiler/codegen/KotlinPoet.kt, compiler/src/main/java/com/squareup/anvil/compiler/codegen/PsiUtils.kt, compiler/src/main/java/com/squareup/anvil/compiler/codegen/dagger/InjectConstructorFactoryGenerator.kt, compiler/src/main/java/com/squareup/anvil/compiler/codegen/dagger/MembersInjectorGenerator.kt, compiler/src/main/java/com/squareup/anvil/compiler/codegen/dagger/ProvidesMethodFactoryGenerator.kt, compiler/src/test/java/com/squareup/anvil/compiler/dagger/Factory.kt, compiler/src/test/java/com/squareup/anvil/compiler/dagger/InjectConstructorFactoryGeneratorTest.kt, compiler/src/test/java/com/squareup/anvil/compiler/dagger/ProvidesMethodFactoryGeneratorTest.kt, compiler/src/test/java/com/squareup/anvil/compiler/dagger/TestClasses.kt
This PR reworks how imports are resolved. Before I implemented an "easy fix, "workaround" or "hack" 🙃  As usual, those things bite one in the long run. Now I resolve all types properly so that Kotlin Poet can add the correct imports.
Fixes #97, #82
=> Fix wrong imports

compiler/src/main/java/com/squareup/anvil/compiler/codegen/PsiUtils.kt, compiler/src/test/java/com/squareup/anvil/compiler/dagger/ProvidesMethodFactoryGeneratorTest.kt
=> Print a better user-friendlier error message for Dagger provider methods with an implicit return type.

dependencies.gradle, sample/app/src/main/java/com/squareup/anvil/sample/RandomModule.kt, sample/app/src/test/java/com/squareup/anvil/sample/RandomModuleTest.kt, sample/scopes/build.gradle, sample/scopes/src/main/java/com/squareup/scopes/SingleIn.kt
=> Add example and test for showing how to setup up single instance per component

integration-tests/tests/build.gradle
Run this check when building the integration tests. This check helps avoiding running into #65 again.
=> Add a check that makes sure that absolute paths aren't used as task inputs.

build.gradle, gradle-plugin/src/main/java/com/squareup/anvil/plugin/AnvilSubplugin.kt
3 changes, 1 in the build system of anvil, the other 2 in the plugin itself.
Replaces https://github.com/square/anvil/pull/133
=> Use TCA apis.

gradle-plugin/src/main/java/com/squareup/anvil/plugin/AnvilSubplugin.kt, integration-tests/tests/build.gradle
Avoid adding the absolute file path for the src gen directory as task input by using a FilesSubpluginOption.
Fixes #65
=> Avoid adding the absolute file path as task input

compiler/src/main/java/com/squareup/anvil/compiler/InterfaceMerger.kt, compiler/src/main/java/com/squareup/anvil/compiler/ModuleMerger.kt, compiler/src/main/java/com/squareup/anvil/compiler/Utils.kt, compiler/src/main/java/com/squareup/anvil/compiler/codegen/BindingModuleGenerator.kt
When resolving the Kotlin type of inner class from dependencies the compiler might fail. It tries to load `my.package.Class$Inner` and fails whereas is should load `my.package.Class.Inner`. I was only able to reproduce this in our Square repository and confirmed that this workaround fixes the bug.
=> Handle inner classes explicitly when resolving the Kotlin type

.github/workflows/ci.yml, compiler/generate_build_properties.gradle, compiler/src/main/java/com/squareup/anvil/compiler/AnvilComponentRegistrar.kt
Use the new public API for registering extensions with a specific order. This will allow us to remove the workaround to register our extension first.
See https://youtrack.jetbrains.com/issue/KT-42103
=> Use Kotlin 1.4.20-M2-158 in CI

compiler/src/main/java/com/squareup/anvil/compiler/codegen/ContributesBindingGenerator.kt, compiler/src/main/java/com/squareup/anvil/compiler/codegen/ContributesToGenerator.kt, compiler/src/test/java/com/squareup/anvil/compiler/ModuleMergerTest.kt
When using Anvil in a module that has strict API Mode enable, `ContributesBindingGenerator` and `ContributesToGenerator` will generate the hint used internally for merging modules and components interface without a visibility modifier and therefore, Kotlin Explicit API will fail the compilation.
Fixes #140.
=> Generated hint for @ContributesBinding and @ContributesTo explicitly defined as internal to support Kotlin 1.4 Explicit API Mode

dependencies.gradle, integration-tests/library/build.gradle, integration-tests/library/src/main/java/com/squareup/anvil/test/Bindings.kt, integration-tests/library/src/main/java/com/squareup/anvil/test/Components.kt, integration-tests/library/src/main/java/com/squareup/anvil/test/Modules.kt, integration-tests/library/src/main/java/com/squareup/anvil/test/Scopes.kt, integration-tests/tests/build.gradle, integration-tests/tests/src/test/java/com/squareup/anvil/test/MergeComponentTest.kt, integration-tests/tests/src/test/java/com/squareup/anvil/test/MergeInterfacesTest.kt, integration-tests/tests/src/test/java/com/squareup/anvil/test/MergeModulesTest.kt
Anvil uses KotlinPoet to generate the Dagger factories in which in the [latest version 1.7.0](https://github.com/square/kotlinpoet/blob/master/docs/changelog.md): _"Generated code is now compatible with the explicit API mode by default."_.
This PR:
- Updates [KotlinPoet to 1.7.2](https://github.com/square/kotlinpoet/releases/tag/1.7.2), as it is required due to the error: [Cannot use KotlinPoet version `1.7.0` with Java 8](https://github.com/square/kotlinpoet/issues/999).
- Updates the sample app to use explicit API mode in the `:sample:scopes` and `:sample:library` modules to show its usage, `:sample:app` module is untouched as it is not a "library" module. If this is not necessary, I can revert the commit.
Fixes #144.
=> Support the explicit API mode when generating Dagger factories

compiler/src/main/java/com/squareup/anvil/compiler/codegen/KotlinPoet.kt, compiler/src/test/java/com/squareup/anvil/compiler/dagger/ProvidesMethodFactoryGeneratorTest.kt, compiler/src/test/java/com/squareup/anvil/compiler/dagger/UppercasePackage/TestClassInUppercasePackage.kt
Fixes #150 
I decided to remove the `ClassName.bestGuess` instead of using it as a fallback because I could not think of a case where this fallback would be required and be reliable enough for it to produce something useful. However, I don't think I understand the full picture and might be missing something important.
=> [#150] Unconventional package names generate correct factories

compiler/src/main/java/com/squareup/anvil/compiler/codegen/PsiUtils.kt, compiler/src/test/java/com/squareup/anvil/compiler/TestUtils.kt, compiler/src/test/java/com/squareup/anvil/compiler/dagger/ComponentDetectorCheckTest.kt, compiler/src/test/java/com/squareup/anvil/compiler/dagger/InjectConstructorFactoryGeneratorTest.kt, compiler/src/test/java/com/squareup/anvil/compiler/dagger/MembersInjectorGeneratorTest.kt, compiler/src/test/java/com/squareup/anvil/compiler/dagger/ProvidesMethodFactoryGeneratorTest.kt
If a classname matches two imports, then try to resolve the type to find the correct one.
Fixes #154
=> Use correct package for import

dependencies.gradle, gradle-plugin/build.gradle
Even though Gradle shows a warning. We need the new APIs.
Github's UI somehow tricked me and PR actually failed.
=> Use the Kotlin 1.4 dependencies in the gradle plugin 

build.gradle, compiler/src/main/java/com/squareup/anvil/compiler/AnvilCommandLineProcessor.kt, compiler/src/main/java/com/squareup/anvil/compiler/AnvilComponentRegistrar.kt, compiler/src/main/java/com/squareup/anvil/compiler/codegen/dagger/AnvilAnnotationDetectorCheck.kt, compiler/src/test/java/com/squareup/anvil/compiler/TestUtils.kt, compiler/src/test/java/com/squareup/anvil/compiler/dagger/AnvilAnnotationDetectorCheckTest.kt, dependencies.gradle, gradle-plugin/src/main/java/com/squareup/anvil/plugin/AnvilExtension.kt, gradle-plugin/src/main/java/com/squareup/anvil/plugin/AnvilPlugin.kt, integration-tests/dagger-factories-only/build.gradle, integration-tests/dagger-factories-only/src/main/java/com/squareup/anvil/test/DaggerModule.kt, integration-tests/dagger-factories-only/src/test/java/com/squareup/anvil/test/GeneratedFactoryTest.kt, settings.gradle
Add a new flag to the Anvil extension so that Anvil will only generate Dagger factories and no other code. The benefit of this that the stub generating Kotlin task can be incremental.
=> Dagger Factories Only

compiler/src/main/java/com/squareup/anvil/compiler/AnvilComponentRegistrar.kt, compiler/src/main/java/com/squareup/anvil/compiler/ReflectionTestUtils.kt, compiler/src/main/java/com/squareup/anvil/compiler/Utils.kt, compiler/src/main/java/com/squareup/anvil/compiler/codegen/KotlinPoet.kt, compiler/src/main/java/com/squareup/anvil/compiler/codegen/PrivateCodeGenerator.kt, compiler/src/main/java/com/squareup/anvil/compiler/codegen/dagger/AssistedFactoryGenerator.kt, compiler/src/main/java/com/squareup/anvil/compiler/codegen/dagger/AssistedInjectGenerator.kt, compiler/src/main/java/com/squareup/anvil/compiler/codegen/dagger/InjectConstructorFactoryGenerator.kt, compiler/src/main/java/com/squareup/anvil/compiler/codegen/dagger/MembersInjectorGenerator.kt, compiler/src/main/java/com/squareup/anvil/compiler/codegen/dagger/ProvidesMethodFactoryGenerator.kt, compiler/src/test/java/com/squareup/anvil/compiler/TestUtils.kt, compiler/src/test/java/com/squareup/anvil/compiler/dagger/AssistedFactoryGeneratorTest.kt, compiler/src/test/java/com/squareup/anvil/compiler/dagger/AssistedInjectGeneratorTest.kt, dependencies.gradle, integration-tests/library/src/main/java/com/squareup/anvil/test/AssistedService.kt, integration-tests/tests/src/test/java/com/squareup/anvil/test/AssistedInjectionTest.kt
Dagger 2.31 has built-in support for assisted injection. Dagger generates code for the classes using the new annotations. Anvil allows to replace the Dagger annotation processor in many modules and generates the necessary code. This PR adds support for assisted injection.
=> #165 Support Dagger's assisted inject and generate necessary code

compiler/src/main/java/com/squareup/anvil/compiler/codegen/dagger/ProvidesMethodFactoryGenerator.kt, compiler/src/test/java/com/squareup/anvil/compiler/dagger/ProvidesMethodFactoryGeneratorTest.kt
This was a false positive.
Fixes #187
=> A provider method inside of a companion object is not abstract. 

.github/workflows/ci.yml
Increase the timeout for jobs that need more time due to the increased number of tests.
Especially the job for Windows is flaky and runs into the timeout.
=> Increase timeout

CHANGELOG.md, compiler/src/main/java/com/squareup/anvil/compiler/codegen/KotlinPoet.kt, compiler/src/main/java/com/squareup/anvil/compiler/codegen/dagger/AssistedFactoryGenerator.kt, compiler/src/main/java/com/squareup/anvil/compiler/codegen/dagger/AssistedInjectGenerator.kt, compiler/src/test/java/com/squareup/anvil/compiler/dagger/AssistedFactoryGeneratorTest.kt, compiler/src/test/java/com/squareup/anvil/compiler/dagger/AssistedInjectGeneratorTest.kt, dependencies.gradle
Initially, Dagger relied on the order of parameters for assisted injection and parameter types had to match between the inject constructor and the factory method. Dagger now introduced a new string identifier `@Assisted("identifier")`. For each parameter they compute a key, which is like a hash of the identifier and the type. The order of parameters is no longer important. Rather, they rely on the keys. There should be no duplicate key and for each key in the inject constructor must be a key in the factory function.
For this PR I upgraded Dagger, updated all tests with the behavior changes, added tests for new edge cases and then fixed all implementations to make the tests pass.
=> Upgrade Dagger. 

compiler/src/test/java/com/squareup/anvil/compiler/ReflectionTestUtils.kt, compiler/src/test/java/com/squareup/anvil/compiler/dagger/AssistedFactoryGeneratorTest.kt, compiler/src/test/java/com/squareup/anvil/compiler/dagger/AssistedInjectGeneratorTest.kt, compiler/src/test/java/com/squareup/anvil/compiler/dagger/MembersInjectorGeneratorTest.kt, compiler/src/test/java/com/squareup/anvil/compiler/dagger/ProvidesMethodFactoryGeneratorTest.kt
* Use data classes in tests instead of implementing equals() manually now that Dagger supports assisted injection for data classes.
* Use a utility function to create objects for a given class object.
=> Clean up tests

CHANGELOG.md, compiler/src/main/java/com/squareup/anvil/compiler/Utils.kt, compiler/src/main/java/com/squareup/anvil/compiler/codegen/PsiUtils.kt, compiler/src/main/java/com/squareup/anvil/compiler/codegen/dagger/ProvidesMethodFactoryGenerator.kt, compiler/src/test/java/com/squareup/anvil/compiler/dagger/ProvidesMethodFactoryGeneratorTest.kt, integration-tests/library/src/main/java/com/squareup/anvil/test/Modules.kt, integration-tests/tests/src/test/java/com/squareup/anvil/test/MergeComponentTest.kt
If a provider function's name is mangled (usually when the function has internal visibility), then use the mangled name to generate the factory.
=> Use the mangled function name to generate the factory for a provider method.

compiler/src/test/java/com/squareup/anvil/compiler/dagger/AssistedFactoryGeneratorTest.kt, dependencies.gradle
And add a test case for an assisted injection scenario that previously failed.
=> Upgrade Dagger 

compiler/src/main/java/com/squareup/anvil/compiler/AnvilCompilationException.kt, compiler/src/main/java/com/squareup/anvil/compiler/Utils.kt, compiler/src/test/java/com/squareup/anvil/compiler/ModuleMergerTest.kt
While debugging an issue, I was unable to find the module this scope threw an exception for, so I added an error message to make it easier to find.
I tried to add a test, but I couldn't figure out where to place it, let me know if any changes are needed.
=> Add error message for missing scope

annotations/src/main/java/com/squareup/anvil/annotations/ContributesBinding.kt, annotations/src/main/java/com/squareup/anvil/annotations/ContributesMultibinding.kt, compiler/src/main/java/com/squareup/anvil/compiler/AnvilComponentRegistrar.kt, compiler/src/main/java/com/squareup/anvil/compiler/InterfaceMerger.kt, compiler/src/main/java/com/squareup/anvil/compiler/ModuleMerger.kt, compiler/src/main/java/com/squareup/anvil/compiler/ModuleMergerIr.kt, compiler/src/main/java/com/squareup/anvil/compiler/Utils.kt, compiler/src/main/java/com/squareup/anvil/compiler/codegen/BindingModuleGenerator.kt, compiler/src/main/java/com/squareup/anvil/compiler/codegen/ContributesBindingGenerator.kt, compiler/src/main/java/com/squareup/anvil/compiler/codegen/ContributesMultibindingGenerator.kt, compiler/src/test/java/com/squareup/anvil/compiler/MergeModulesTest.kt, compiler/src/test/java/com/squareup/anvil/compiler/ModuleMergerTest.kt, compiler/src/test/java/com/squareup/anvil/compiler/TestUtils.kt, compiler/src/test/java/com/squareup/anvil/compiler/codegen/BindingModuleMultibindingSetTest.kt, compiler/src/test/java/com/squareup/anvil/compiler/codegen/BindingModuleQualifierTest.kt, compiler/src/test/java/com/squareup/anvil/compiler/codegen/ContributesMultibindingGeneratorTest.kt, integration-tests/library/src/main/java/com/squareup/anvil/test/Bindings.kt, integration-tests/tests/src/test/java/com/squareup/anvil/test/MergeComponentTest.kt, integration-tests/tests/src/test/java/com/squareup/anvil/test/MergeModulesTest.kt
This will partially resolve #152. This PR adds support for generating multibindings into sets. Generating multibindings for maps will be a separate PR #219. 
This PR is quite large and broken down into smaller commits. There are plenty of tests, which "contributeTo" (Do you see what I did here, yes, I'm very funny) to the size of the PR. In single commits you my find a TODO that is resolved in a later commit or a follow-up PR in #217 or #218. 
From the consumer side contributing multibindings is very similar to bindings and both annotations can be used in conjunction. Qualifiers are supported as well.
```kotlin
@ContributesBinding(SubScope::class)
@ContributesMultibinding(SubScope::class, ignoreQualifier = true)
@Named("middle")
object SomeType : Parent
```
=> Generate methods for contributed multibindings

annotations/src/main/java/com/squareup/anvil/annotations/ContributesMultibinding.kt, compiler/src/main/java/com/squareup/anvil/compiler/Utils.kt, compiler/src/main/java/com/squareup/anvil/compiler/codegen/BindingModuleGenerator.kt, compiler/src/main/java/com/squareup/anvil/compiler/codegen/ContributesMultibindingGenerator.kt, compiler/src/test/java/com/squareup/anvil/compiler/TestUtils.kt, compiler/src/test/java/com/squareup/anvil/compiler/codegen/BindingModuleMultibindingMapTest.kt, integration-tests/library/src/main/java/com/squareup/anvil/test/MapBindings.kt, integration-tests/tests/src/test/java/com/squareup/anvil/test/MergeComponentTest.kt
If a class is annotated with @ContributesMultibinding and a map key annotation, then Anvil will generate a map multibinding method.
This PR completes #152.
=> Generate multibinding methods for contributed map multibindings. 

CHANGELOG.md, annotations/src/main/java/com/squareup/anvil/annotations/ContributesBinding.kt, compiler/src/main/java/com/squareup/anvil/compiler/Utils.kt, compiler/src/main/java/com/squareup/anvil/compiler/codegen/BindingModuleGenerator.kt, compiler/src/test/java/com/squareup/anvil/compiler/codegen/BindingModulePriorityTest.kt, integration-tests/library/src/main/java/com/squareup/anvil/test/PriorityBindings.kt, integration-tests/tests/src/test/java/com/squareup/anvil/test/MergeComponentTest.kt
Add a priority field to @ContributesBinding to replace other contributed bindings. The priority should only be used, if you don't have access to the replaced class at compile time. Otherwise prefer the `replaces` field.
Fixes #161
=> Support different priorities for contributed bindings

compiler/src/main/java/com/squareup/anvil/compiler/ClassScanner.kt, compiler/src/main/java/com/squareup/anvil/compiler/ModuleMerger.kt, compiler/src/main/java/com/squareup/anvil/compiler/ModuleMergerIr.kt, compiler/src/main/java/com/squareup/anvil/compiler/Utils.kt, compiler/src/main/java/com/squareup/anvil/compiler/codegen/BindingModuleGenerator.kt, compiler/src/main/java/com/squareup/anvil/compiler/codegen/ContributesBindingGenerator.kt, compiler/src/main/java/com/squareup/anvil/compiler/codegen/ContributesMultibindingGenerator.kt, compiler/src/main/java/com/squareup/anvil/compiler/codegen/ContributesToGenerator.kt, compiler/src/main/java/com/squareup/anvil/compiler/codegen/KotlinPoet.kt, compiler/src/main/java/com/squareup/anvil/compiler/codegen/PsiUtils.kt, compiler/src/main/java/com/squareup/anvil/compiler/codegen/dagger/AssistedFactoryGenerator.kt, compiler/src/main/java/com/squareup/anvil/compiler/codegen/dagger/AssistedInjectGenerator.kt, compiler/src/main/java/com/squareup/anvil/compiler/codegen/dagger/InjectConstructorFactoryGenerator.kt, compiler/src/main/java/com/squareup/anvil/compiler/codegen/dagger/MembersInjectorGenerator.kt, compiler/src/main/java/com/squareup/anvil/compiler/codegen/dagger/ProvidesMethodFactoryGenerator.kt, compiler/src/test/java/com/squareup/anvil/compiler/InterfaceMergerTest.kt, compiler/src/test/java/com/squareup/anvil/compiler/MergeModulesTest.kt, compiler/src/test/java/com/squareup/anvil/compiler/ModuleMergerTest.kt, compiler/src/test/java/com/squareup/anvil/compiler/TestUtils.kt, compiler/src/test/java/com/squareup/anvil/compiler/codegen/BindingModuleGeneratorTest.kt, compiler/src/test/java/com/squareup/anvil/compiler/dagger/AssistedFactoryGeneratorTest.kt, compiler/src/test/java/com/squareup/anvil/compiler/dagger/InjectConstructorFactoryGeneratorTest.kt, compiler/src/test/java/com/squareup/anvil/compiler/dagger/MembersInjectorGeneratorTest.kt, compiler/src/test/java/com/squareup/anvil/compiler/dagger/ProvidesMethodFactoryGeneratorTest.kt
The compiler APIs return "<root>" as fully qualified name for the root package, but we want to default to an empty string instead.
Fixes #227
=> Fix crashes when classes don't use any package. 

compiler/src/test/java/com/squareup/anvil/compiler/codegen/BindingModulePriorityTest.kt
I thought I detected a bug in Anvil while testing the release in our codebase, but it turns out that our project was configured wrong. I wanted to keep nonetheless for more confidence and to avoid regressions.
=> Add more tests to verify that exclusions and replacements don't result in duplicate bindings

compiler/src/main/java/com/squareup/anvil/compiler/codegen/ContributesBindingGenerator.kt, compiler/src/main/java/com/squareup/anvil/compiler/codegen/ContributesMultibindingGenerator.kt, compiler/src/main/java/com/squareup/anvil/compiler/codegen/PsiUtils.kt, compiler/src/test/java/com/squareup/anvil/compiler/codegen/ContributesBindingGeneratorTest.kt, compiler/src/test/java/com/squareup/anvil/compiler/codegen/ContributesMultibindingGeneratorTest.kt
That's a regression I noticed while testing the new version in our codebase.
=> If the bound type is specified, then multiple super types are allowed.

compiler/src/main/java/com/squareup/anvil/compiler/codegen/PsiUtils.kt, compiler/src/test/java/com/squareup/anvil/compiler/codegen/ContributesToGeneratorTest.kt
It actually didn't look for the specific annotation we meant, but rather all Kotlin annotations we care about.
Fixes #232
=> Fix the check for kotlin annotations. 

build.gradle, gradle-plugin/build.gradle
This should avoid any issue with the [upcoming sunset](https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/) of them.
=> Remove bintray and jcenter repositories

compiler/src/main/java/com/squareup/anvil/compiler/codegen/KotlinPoet.kt, compiler/src/test/java/com/squareup/anvil/compiler/dagger/AssistedFactoryGeneratorTest.kt
There's always way more test code than actual changes in the compiler plugin.
=> Handle Lazy assisted parameters properly in generated assisted factories

compiler-utils/src/main/java/com/squareup/anvil/compiler/internal/AnvilModuleDescriptor.kt, compiler-utils/src/main/java/com/squareup/anvil/compiler/internal/CompilerUtils.kt, compiler-utils/src/main/java/com/squareup/anvil/compiler/internal/KotlinPoetUtils.kt, compiler-utils/src/main/java/com/squareup/anvil/compiler/internal/PsiUtils.kt, compiler/src/main/java/com/squareup/anvil/compiler/codegen/CodeGenerationExtension.kt, compiler/src/main/java/com/squareup/anvil/compiler/codegen/ContributesBindingGenerator.kt, compiler/src/main/java/com/squareup/anvil/compiler/codegen/PrivateCodeGenerator.kt, compiler/src/main/java/com/squareup/anvil/compiler/codegen/RealAnvilModuleDescriptor.kt, compiler/src/test/java/com/squareup/anvil/compiler/MergeModulesTest.kt, integration-tests/code-generator-tests/build.gradle, integration-tests/code-generator-tests/src/test/java/com/squareup/anvil/test/GeneratedCodeTest.kt, integration-tests/code-generator/src/main/java/com/squareup/anvil/test/TestCodeGenerator.kt
Introduce a new API to check if a FqName can be resolved. In the implementation also check for the FqName in generated code, which is critical for some code generators.
Before we only resolved the class descriptor and based upon the result decided if the FqName is valid, which was never true for generated code.
Add an integration test for generating a class that is referenced in non-generated code.
Fixes #283, the solution is based on #282.
=> Improve check if FqName exists

compiler/src/main/java/com/squareup/anvil/compiler/codegen/BindingModuleGenerator.kt
This is a regression that was introduced while working on the new CodeGenerator API.
=> Use the correct replacement classes. 

compiler-utils/src/main/java/com/squareup/anvil/compiler/internal/FqName.kt, compiler-utils/src/main/java/com/squareup/anvil/compiler/internal/PsiUtils.kt, compiler/src/main/java/com/squareup/anvil/compiler/Utils.kt
A little simpler to use than the `.java.canonicalName` boilerplate
=> Introduce KClass<*>.fqName helper extension

compiler-utils/src/testFixtures/java/com/squareup/anvil/compiler/internal/testing/TestUtils.kt
kotlin-compile-testing under the hood will otherwise create tmp dirs that are impossible to get manually without access to the `KotlinCompilation`. This allows for customizing that, such as with the parent test's own `TemporaryFolder`.
=> Add a workingDir param to anvilCompile for test folder access

compiler/src/main/java/com/squareup/anvil/compiler/ModuleMerger.kt, compiler/src/main/java/com/squareup/anvil/compiler/ModuleMergerIr.kt, compiler/src/main/java/com/squareup/anvil/compiler/codegen/BindingModuleGenerator.kt, compiler/src/test/java/com/squareup/anvil/compiler/ModuleMergerTest.kt, compiler/src/test/java/com/squareup/anvil/compiler/codegen/BindingModuleGeneratorTest.kt, compiler/src/test/java/com/squareup/anvil/compiler/codegen/BindingModuleMultibindingSetTest.kt
Fixes #301. Modules and bindings are no longer replaced if the replacement is declared by an excluded module.
Open to better ways of accomplishing this as I found the fq and psi class work a little tricky.
=> Fix replaced modules and bindings by excluded modules

gradle-plugin/src/main/java/com/squareup/anvil/plugin/AnvilPlugin.kt, gradle-plugin/src/main/java/com/squareup/anvil/plugin/CheckMixedSourceSet.kt, integration-tests/code-generator-tests/build.gradle, integration-tests/mpp/android-module/build.gradle
Rework how the Gradle plugin sets up its configuration, Gradle tasks and patches for other Gradle tasks. Instead of querying the tasks manually and checking which plugins are applied, use the callback methods from the Kotlin Gradle Plugin. With this change we can remove a lot from our custom logic.
This also allows us to easily create an Anvil configuration for each build variant separately. This allows to add custom code generators to specific build types only.
This refactoring is needed for #100.
=> Refactor the Gradle plugin and create multiple Anvil configurations.

gradle-plugin/src/main/java/com/squareup/anvil/plugin/AnvilExtension.kt, gradle-plugin/src/main/java/com/squareup/anvil/plugin/AnvilPlugin.kt, gradle-plugin/src/main/java/com/squareup/anvil/plugin/VariantFilter.kt, integration-tests/mpp/android-module/build.gradle, integration-tests/tests/build.gradle
Introduce a new `VariantFilter` for the Gradle extension. This API allows you to enable and disable Anvil for specific variants. 
Allow to override `generateDaggerFactories`, `generateDaggerFactoriesOnly` and `disableComponentMerging` through the variant filter.
This resolves #100.
=> Introduce a variant filter

compiler-utils/src/main/java/com/squareup/anvil/compiler/internal/KotlinPoetUtils.kt
This optimization allows for short-circuiting the type resolution if the desired raw type isn't applicable
=> Add rawTypeFilter to KotlinType.asTypeName()

gradle.properties
Deprecated since Kotlin 1.5.20.
=> Remove deprecated Kotlin build flag.

gradle-plugin/src/main/java/com/squareup/anvil/plugin/CheckMixedSourceSet.kt
The former is deprecated and the latter is what should be used instead
https://docs.gradle.org/current/javadoc/org/gradle/api/plugins/JavaPluginConvention.html
=> Replace JavaPluginConvention with JavaPluginExtension

compiler-utils/src/testFixtures/java/com/squareup/anvil/compiler/internal/testing/ReflectionTestUtils.kt, compiler-utils/src/testFixtures/java/com/squareup/anvil/compiler/internal/testing/TestUtils.kt, compiler/src/main/java/com/squareup/anvil/compiler/codegen/dagger/AssistedInjectGenerator.kt, compiler/src/main/java/com/squareup/anvil/compiler/codegen/dagger/InjectConstructorFactoryGenerator.kt, compiler/src/main/java/com/squareup/anvil/compiler/codegen/dagger/MembersInjectionUtils.kt, compiler/src/main/java/com/squareup/anvil/compiler/codegen/dagger/MembersInjectorGenerator.kt, compiler/src/test/java/com/squareup/anvil/compiler/TestUtils.kt, compiler/src/test/java/com/squareup/anvil/compiler/dagger/AssistedFactoryGeneratorTest.kt, compiler/src/test/java/com/squareup/anvil/compiler/dagger/MembersInjectorGeneratorTest.kt
Resolves #342 and also leaves some important consolidated logic toe-holds along the way for helping with #341, #340, #339, and #343
=> Account for member injection in assisted types

compiler-utils/src/main/java/com/squareup/anvil/compiler/internal/AnvilModuleDescriptor.kt, compiler-utils/src/main/java/com/squareup/anvil/compiler/internal/KotlinPoetUtils.kt, compiler-utils/src/main/java/com/squareup/anvil/compiler/internal/PsiUtils.kt, compiler-utils/src/testFixtures/java/com/squareup/anvil/compiler/internal/testing/TestUtils.kt, compiler/src/main/java/com/squareup/anvil/compiler/codegen/DescriptorUtils.kt, compiler/src/main/java/com/squareup/anvil/compiler/codegen/KotlinPoetUtils.kt, compiler/src/main/java/com/squareup/anvil/compiler/codegen/Parameter.kt, compiler/src/main/java/com/squareup/anvil/compiler/codegen/RealAnvilModuleDescriptor.kt, compiler/src/main/java/com/squareup/anvil/compiler/codegen/dagger/AssistedInjectGenerator.kt, compiler/src/main/java/com/squareup/anvil/compiler/codegen/dagger/InjectConstructorFactoryGenerator.kt, compiler/src/main/java/com/squareup/anvil/compiler/codegen/dagger/MembersInjectionUtils.kt, compiler/src/main/java/com/squareup/anvil/compiler/codegen/dagger/MembersInjectorGenerator.kt, compiler/src/main/java/com/squareup/anvil/compiler/codegen/dagger/ProvidesMethodFactoryGenerator.kt, compiler/src/test/java/com/squareup/anvil/compiler/dagger/InjectConstructorFactoryGeneratorTest.kt, compiler/src/test/java/com/squareup/anvil/compiler/dagger/MembersInjectorGeneratorTest.kt
fixes #343
Basically, these changes use PSI to find superclasses by parsing the FqName from a `KtClassOrObject`'s supertype list, then using that to look up the super's `KtClassOrObject` from `RealAnvilModuleDescriptor`.  When this method no longer returns results, that means any additional super-types come from other modules/dependencies and it's safe to use descriptors.
This required forking a lot of the psi-based parsing for `Parameter` for use with Descriptor types.  
I also turned `Parameter` into an interface and created `MemberInjectParameter`, which is the same thing except for a few extra fields for member-injected specific stuff.  I don't love the names I chose, and there are a few options I'm on the fence about, like using interface delegation for MemberInjectedParameter and …
=> support member injection for superclasses

gradle-plugin/src/main/java/com/squareup/anvil/plugin/AnvilPlugin.kt
Due to this bug custom code generators weren't picked up in JVM modules if you used `anvil('my-code-generator')'`.
Fixes #368
=> Make `anvilMain()` extend the `anvil()` configuration in JVM modules.

compiler-utils/src/testFixtures/java/com/squareup/anvil/compiler/internal/testing/TestUtils.kt
Since `configureAnvil` manipulates the working dir, this should be set first
=> Fix ordering of compileAnvil calls

.github/workflows/ci.yml
Anvil will be migrated to Kotlin 1.6 in a separate PR.
=> Test Anvil with Kotlin 1.6.0 stable in CI.

compiler-utils/src/main/java/com/squareup/anvil/compiler/internal/PsiUtils.kt, compiler-utils/src/testFixtures/java/com/squareup/anvil/compiler/internal/testing/TestUtils.kt
This is another special type that I _believe_ is used for cases where Kotlinc knows a given descriptor is not null due to some external indication like `@NonNull` or a JSR 305/jSpecify annotation. I'm unable to repro it in a test but I can repro it in our codebase (which has a setup that leads me to believe the JSR 305 case, where it trips up on a java base class from an upstream module sitting in a jsr305-dictated package).
I've at least been able to confirm that our code compiles with this fix and also found some prior art in kotlinc that suggests this is the right path to unwrapping [here](https://github.com/JetBrains/kotlin/blob/9ee0d6b60ac4f0ea0ccc5dd01146bab92fabcdf2/core/descriptors/src/org/jetbrains/kotlin/types/TypeUtils.java#L448-L458.
=> Fix DefinitelyNotNullTye

compiler-utils/src/main/java/com/squareup/anvil/compiler/internal/CompilerUtils.kt, compiler-utils/src/main/java/com/squareup/anvil/compiler/internal/PsiUtils.kt, compiler/src/main/java/com/squareup/anvil/compiler/InterfaceMerger.kt, compiler/src/main/java/com/squareup/anvil/compiler/codegen/ContributesSubcomponentHandlerGenerator.kt, compiler/src/main/java/com/squareup/anvil/compiler/codegen/dagger/AssistedFactoryGenerator.kt, compiler/src/test/java/com/squareup/anvil/compiler/codegen/ContributesSubcomponentHandlerGeneratorTest.kt
This PR solves an issue that the same subcomponent is generated, what results in very surprising results. We now make sure that each generated subcomponent is unique.
=> Avoid duplicate generated subcomponents

compiler/src/main/java/com/squareup/anvil/compiler/codegen/CodeGenerationExtension.kt
By resolving types before clearing the output dir, we are able to avoid https://youtrack.jetbrains.com/issue/KT-49340.
=> Work around KT-49340

compiler/src/main/java/com/squareup/anvil/compiler/codegen/BindingModuleGenerator.kt
That seems to happen in very rare cases in modules with a stub generating tasks and Kotlin compile task during certain incremental changes.
Fixes #460
=> Filter bindings for the same type. 

compiler/src/main/java/com/squareup/anvil/compiler/ClassScannerIr.kt, compiler/src/main/java/com/squareup/anvil/compiler/IrUtils.kt, compiler/src/main/java/com/squareup/anvil/compiler/ModuleMerger.kt, compiler/src/main/java/com/squareup/anvil/compiler/ModuleMergerIr.kt, compiler/src/main/java/com/squareup/anvil/compiler/Utils.kt, compiler/src/main/java/com/squareup/anvil/compiler/codegen/BindingModuleGenerator.kt, compiler/src/main/java/com/squareup/anvil/compiler/codegen/ContributesSubcomponentHandlerGenerator.kt, compiler/src/test/java/com/squareup/anvil/compiler/codegen/ContributesSubcomponentHandlerGeneratorTest.kt
And don't use `@ContributesBinding`. The annotation leads to potential duplicate bindings. We used a similar solution for parent component interfaces.
Fixes #459
=> Manually bind the generated Dagger factory for contribute subcomponents

compiler-utils/src/main/java/com/squareup/anvil/compiler/internal/PsiUtils.kt, compiler/src/test/java/com/squareup/anvil/compiler/dagger/InjectConstructorFactoryGeneratorTest.kt
That was a regression introduced by https://github.com/square/anvil/commit/403e83577682faa241f987b2c93661344b4d6a29. I found while testing the new release.
=> Support resolving an `FqName` for lambdas.

compiler-utils/src/testFixtures/java/com/squareup/anvil/compiler/internal/testing/AnvilCompilation.kt, dependencies.gradle
And remove the workaround that was necessary until now.
This PR requires Kotlin 1.6 first, though. I wanted to put it up nonetheless.
=> Upgrade the compile testing library 

compiler-utils/src/main/java/com/squareup/anvil/compiler/internal/ClassReference.kt, compiler-utils/src/main/java/com/squareup/anvil/compiler/internal/FqName.kt, compiler-utils/src/main/java/com/squareup/anvil/compiler/internal/KotlinPoetUtils.kt, compiler-utils/src/main/java/com/squareup/anvil/compiler/internal/PsiUtils.kt, compiler-utils/src/main/java/com/squareup/anvil/compiler/internal/reference/AnvilModuleDescriptor.kt, compiler/src/main/java/com/squareup/anvil/compiler/codegen/BindingModuleGenerator.kt, compiler/src/main/java/com/squareup/anvil/compiler/codegen/CodeGenerationExtension.kt, compiler/src/main/java/com/squareup/anvil/compiler/codegen/ContributedBinding.kt, compiler/src/main/java/com/squareup/anvil/compiler/codegen/ContributesBindingGenerator.kt, compiler/src/main/java/com/squareup/anvil/compiler/codegen/ContributesMultibindingGenerator.kt, compiler/src/main/java/com/squareup/anvil/compiler/codegen/ContributesSubcomponentGenerator.kt, compiler/src/main/java/com/squareup/anvil/compiler/codegen/ContributesSubcomponentHandlerGenerator.kt, compiler/src/main/java/com/squareup/anvil/compiler/codegen/ContributesToGenerator.kt, compiler/src/main/java/com/squareup/anvil/compiler/codegen/dagger/AnvilAnnotationDetectorCheck.kt, compiler/src/main/java/com/squareup/anvil/compiler/codegen/dagger/AnvilMergeAnnotationDetectorCheck.kt, compiler/src/main/java/com/squareup/anvil/compiler/codegen/dagger/AssistedFactoryGenerator.kt, compiler/src/main/java/com/squareup/anvil/compiler/codegen/dagger/AssistedInjectGenerator.kt, compiler/src/main/java/com/squareup/anvil/compiler/codegen/dagger/ComponentDetectorCheck.kt, compiler/src/main/java/com/squareup/anvil/compiler/codegen/dagger/InjectConstructorFactoryGenerator.kt, compiler/src/main/java/com/squareup/anvil/compiler/codegen/dagger/MembersInjectorGenerator.kt, compiler/src/main/java/com/squareup/anvil/compiler/codegen/dagger/ProvidesMethodFactoryGenerator.kt, compiler/src/main/java/com/squareup/anvil/compiler/codegen/reference/RealAnvilModuleDescriptor.kt, compiler/src/test/java/com/squareup/anvil/compiler/codegen/CodeGenerationExtensionTest.kt, compiler/src/test/java/com/squareup/anvil/compiler/codegen/ContributesSubcomponentHandlerGeneratorTest.kt, integration-tests/code-generator/src/main/java/com/squareup/anvil/test/TestCodeGenerator.kt, integration-tests/code-generator/src/main/java/com/squareup/anvil/test/TestWithKaptCodeGenerator.kt
Combine some of the utility functions. Always make sure that the receiver of extension function is the type the utility is made for and not the module descriptor. This improves discoverability.
=> Move `AnvilModuleDescriptor` into a new, more specific package.

compiler-utils/src/main/java/com/squareup/anvil/compiler/internal/CompilerUtils.kt, compiler-utils/src/main/java/com/squareup/anvil/compiler/internal/KotlinPoetUtils.kt, compiler-utils/src/main/java/com/squareup/anvil/compiler/internal/PsiUtils.kt, compiler-utils/src/main/java/com/squareup/anvil/compiler/internal/reference/AnvilModuleDescriptor.kt, compiler-utils/src/main/java/com/squareup/anvil/compiler/internal/reference/ClassReference.kt, compiler-utils/src/main/java/com/squareup/anvil/compiler/internal/reference/FunctionReference.kt, compiler/src/main/java/com/squareup/anvil/compiler/ClassScanner.kt, compiler/src/main/java/com/squareup/anvil/compiler/InterfaceMerger.kt, compiler/src/main/java/com/squareup/anvil/compiler/ModuleMerger.kt, compiler/src/main/java/com/squareup/anvil/compiler/Utils.kt, compiler/src/main/java/com/squareup/anvil/compiler/codegen/ContributedBinding.kt, compiler/src/main/java/com/squareup/anvil/compiler/codegen/ContributesBindingGenerator.kt, compiler/src/main/java/com/squareup/anvil/compiler/codegen/ContributesMultibindingGenerator.kt, compiler/src/main/java/com/squareup/anvil/compiler/codegen/DescriptorUtils.kt, compiler/src/main/java/com/squareup/anvil/compiler/codegen/reference/RealAnvilModuleDescriptor.kt
Cache the results, because these operations are heavy and can add up.
=> Reduce the number of times we resolve class descriptors

compiler-utils/src/main/java/com/squareup/anvil/compiler/internal/PsiUtils.kt, compiler-utils/src/main/java/com/squareup/anvil/compiler/internal/reference/AnnotationReference.kt, compiler-utils/src/main/java/com/squareup/anvil/compiler/internal/reference/AnvilModuleDescriptor.kt, compiler-utils/src/main/java/com/squareup/anvil/compiler/internal/reference/ClassReference.kt, compiler-utils/src/main/java/com/squareup/anvil/compiler/internal/reference/FunctionReference.kt, compiler/src/main/java/com/squareup/anvil/compiler/InterfaceMerger.kt, compiler/src/main/java/com/squareup/anvil/compiler/ModuleMerger.kt, compiler/src/main/java/com/squareup/anvil/compiler/codegen/BindingModuleGenerator.kt, compiler/src/main/java/com/squareup/anvil/compiler/codegen/ContributedBinding.kt, compiler/src/main/java/com/squareup/anvil/compiler/codegen/ContributesSubcomponentGenerator.kt, compiler/src/main/java/com/squareup/anvil/compiler/codegen/ContributesSubcomponentHandlerGenerator.kt, compiler/src/main/java/com/squareup/anvil/compiler/codegen/dagger/AssistedFactoryGenerator.kt, compiler/src/main/java/com/squareup/anvil/compiler/codegen/dagger/MembersInjectionUtils.kt, compiler/src/main/java/com/squareup/anvil/compiler/codegen/reference/RealAnvilModuleDescriptor.kt
This avoid parsing / resolving the types and symbols over and over again.
=> Cache instances of `ClassReference`, `AnnotationReference` and `FunctionReference`

CHANGELOG.md, gradle-plugin/src/main/java/com/squareup/anvil/plugin/AnvilExtension.kt, gradle.properties
This will be a new major release. Many of Anvil's internals will be rewritten. It makes sense to remove these deprecated APIs at the same time.
=> Remove APIs that have been deprecated for a long time in the Gradle plugin.

compiler-utils/src/main/java/com/squareup/anvil/compiler/internal/KotlinPoetUtils.kt, compiler/src/test/java/com/squareup/anvil/compiler/codegen/CodeGenerationExtensionTest.kt
It's impossible to suppress these errors in generated code on the file level for the user, so we must opt-out of all these checks. It's not a bad thing, because the user already must opt-into these features on the usage side.
Fixes #488.
=> Suppress errors for experimental APIs in generated code.

compiler-api/src/main/java/com/squareup/anvil/compiler/api/AnvilCompilationException.kt, compiler-utils/src/main/java/com/squareup/anvil/compiler/internal/PsiUtils.kt, compiler-utils/src/main/java/com/squareup/anvil/compiler/internal/reference/AnvilModuleDescriptor.kt, compiler-utils/src/main/java/com/squareup/anvil/compiler/internal/reference/ClassReference.kt, compiler-utils/src/main/java/com/squareup/anvil/compiler/internal/reference/FunctionReference.kt, compiler-utils/src/main/java/com/squareup/anvil/compiler/internal/reference/ParameterReference.kt, compiler/src/main/java/com/squareup/anvil/compiler/codegen/ContributesSubcomponentGenerator.kt, compiler/src/main/java/com/squareup/anvil/compiler/codegen/ContributesSubcomponentHandlerGenerator.kt, compiler/src/main/java/com/squareup/anvil/compiler/codegen/dagger/AssistedFactoryGenerator.kt, compiler/src/test/java/com/squareup/anvil/compiler/dagger/AssistedFactoryGeneratorTest.kt
That required moving many utilities around to better places, but we were also able to delete some sketch pieces.
=> Convert `AssistedFactoryGenerator` to rely on `ClassReference` only. 

.github/workflows/ci.yml, dependencies.gradle
Don't run the entire test suite for the Windows job, because we don't need to and it's the slowest of all jobs. The job only makes sure that we don't have any incompatibilities and therefore skipping the Dagger tests is fine.
=> Improve CI times of the Windows job.

compiler-utils/src/main/java/com/squareup/anvil/compiler/internal/CompilerUtils.kt, compiler-utils/src/main/java/com/squareup/anvil/compiler/internal/PsiUtils.kt, compiler-utils/src/main/java/com/squareup/anvil/compiler/internal/reference/AnnotationArgumentReference.kt, compiler-utils/src/main/java/com/squareup/anvil/compiler/internal/reference/AnnotationReference.kt, compiler-utils/src/main/java/com/squareup/anvil/compiler/internal/reference/ClassReference.kt, compiler-utils/src/main/java/com/squareup/anvil/compiler/internal/reference/PsiToAnnotationSpecHelper.kt, compiler/src/main/java/com/squareup/anvil/compiler/AnvilComponentRegistrar.kt, compiler/src/main/java/com/squareup/anvil/compiler/ClassScanner.kt, compiler/src/main/java/com/squareup/anvil/compiler/ClassScannerIr.kt, compiler/src/main/java/com/squareup/anvil/compiler/InterfaceMerger.kt, compiler/src/main/java/com/squareup/anvil/compiler/ModuleMerger.kt, compiler/src/main/java/com/squareup/anvil/compiler/ModuleMergerIr.kt, compiler/src/main/java/com/squareup/anvil/compiler/Utils.kt, compiler/src/main/java/com/squareup/anvil/compiler/codegen/BindingModuleGenerator.kt, compiler/src/main/java/com/squareup/anvil/compiler/codegen/ContributedBinding.kt, compiler/src/main/java/com/squareup/anvil/compiler/codegen/ContributesSubcomponentHandlerGenerator.kt, compiler/src/main/java/com/squareup/anvil/compiler/codegen/dagger/DaggerGenerationUtils.kt, compiler/src/main/java/com/squareup/anvil/compiler/codegen/dagger/MembersInjectorGenerator.kt, compiler/src/main/java/com/squareup/anvil/compiler/codegen/reference/RealAnvilModuleDescriptor.kt, compiler/src/test/java/com/squareup/anvil/compiler/InterfaceMergerTest.kt, compiler/src/test/java/com/squareup/anvil/compiler/ModuleMergerTest.kt, compiler/src/test/java/com/squareup/anvil/compiler/internal/reference/ClassReferenceTest.kt
* Add the option to get the name of an annotation argument.
* Clean up the utilities within `ClassReference`.
* Remove several unused or deprecated functions, clean up TODOs and use our reference implementations more broadly.
=> Delete deprecated functions

compiler/src/main/java/com/squareup/anvil/compiler/InterfaceMerger.kt, compiler/src/main/java/com/squareup/anvil/compiler/IrUtils.kt, compiler/src/main/java/com/squareup/anvil/compiler/ModuleMerger.kt, compiler/src/main/java/com/squareup/anvil/compiler/ModuleMergerIr.kt, compiler/src/main/java/com/squareup/anvil/compiler/Utils.kt, compiler/src/test/java/com/squareup/anvil/compiler/ModuleMergerTest.kt
=> Ignore classes without a classId when merging interfaces and modules

annotations/src/main/java/com/squareup/anvil/annotations/ContributesTo.kt, compiler-utils/src/testFixtures/java/com/squareup/anvil/compiler/internal/testing/AnvilCompilation.kt, compiler/src/main/java/com/squareup/anvil/compiler/ClassScanner.kt, compiler/src/main/java/com/squareup/anvil/compiler/ClassScannerIr.kt, compiler/src/main/java/com/squareup/anvil/compiler/InterfaceMerger.kt, compiler/src/main/java/com/squareup/anvil/compiler/ModuleMerger.kt, compiler/src/main/java/com/squareup/anvil/compiler/ModuleMergerIr.kt, compiler/src/main/java/com/squareup/anvil/compiler/Utils.kt, compiler/src/main/java/com/squareup/anvil/compiler/codegen/AnnotationReferenceExtensions.kt, compiler/src/main/java/com/squareup/anvil/compiler/codegen/BindingModuleGenerator.kt, compiler/src/main/java/com/squareup/anvil/compiler/codegen/ContributesSubcomponentHandlerGenerator.kt, compiler/src/main/java/com/squareup/anvil/compiler/codegen/ContributesToGenerator.kt, compiler/src/test/java/com/squareup/anvil/compiler/InterfaceMergerTest.kt, compiler/src/test/java/com/squareup/anvil/compiler/MergeModulesTest.kt, compiler/src/test/java/com/squareup/anvil/compiler/ModuleMergerTest.kt, compiler/src/test/java/com/squareup/anvil/compiler/TestUtils.kt, compiler/src/test/java/com/squareup/anvil/compiler/codegen/ContributesSubcomponentHandlerGeneratorTest.kt, compiler/src/test/java/com/squareup/anvil/compiler/codegen/ContributesToGeneratorTest.kt, docs/INTERNALS.md, integration-tests/library/src/main/java/com/squareup/anvil/test/RepeatableContributions.kt, integration-tests/tests/src/test/java/com/squareup/anvil/test/RepeatedContributionsTest.kt
While you now can have multiple `@ContributesTo` annotations for Dagger modules and component interfaces, they all must have a different scope (contributing to the same scope twice is redundant).
=> Make `@ContributesTo` repeatable.

compiler/src/main/java/com/squareup/anvil/compiler/ClassScanner.kt
The duplicate properties occasionally crop up when making incremental changes, similar to the duplicate bindings issue in #460.
Fixes #565
=> Filter duplicate generated properties.

compiler/src/main/java/com/squareup/anvil/compiler/codegen/AnnotationReferenceExtensions.kt, compiler/src/main/java/com/squareup/anvil/compiler/codegen/BindingModuleGenerator.kt, compiler/src/main/java/com/squareup/anvil/compiler/codegen/ContributedBinding.kt, compiler/src/main/java/com/squareup/anvil/compiler/codegen/ContributesBindingGenerator.kt, compiler/src/main/java/com/squareup/anvil/compiler/codegen/ContributesMultibindingGenerator.kt, compiler/src/test/java/com/squareup/anvil/compiler/TestUtils.kt, compiler/src/test/java/com/squareup/anvil/compiler/codegen/BindingModuleGeneratorTest.kt, compiler/src/test/java/com/squareup/anvil/compiler/codegen/BindingModuleMultibindingSetTest.kt, compiler/src/test/java/com/squareup/anvil/compiler/codegen/ContributesBindingGeneratorTest.kt, compiler/src/test/java/com/squareup/anvil/compiler/codegen/ContributesMultibindingGeneratorTest.kt, compiler/src/test/java/com/squareup/anvil/compiler/dagger/ProvidesMethodFactoryGeneratorTest.kt
Allow contributing multiple bindings with the same scope as long as they have a different bound type. Contributing multiple bindings with the same scope and same bound type is an error.
=> Allow contributing multiple bindings with the same scope.

compiler-utils/src/main/java/com/squareup/anvil/compiler/internal/reference/ClassReference.kt, compiler/src/test/java/com/squareup/anvil/compiler/internal/reference/ClassReferenceTest.kt
=> Add a utility to convert a `ClassReference` to a `TypeName` and respect the type parameters

compiler-utils/src/main/java/com/squareup/anvil/compiler/internal/DescriptorUtils.kt, compiler-utils/src/main/java/com/squareup/anvil/compiler/internal/reference/AnnotationArgumentReference.kt, compiler/src/test/java/com/squareup/anvil/compiler/internal/reference/AnnotationReferenceTest.kt
We didn't handle all cases properly when it came to resolving imports. The test coverage is better now and many (all?) of the previous failing cases are successful now.
Fixes #570
=> Fix resolving constants as annotation arguments.

compiler/src/main/java/com/squareup/anvil/compiler/codegen/dagger/ProvidesMethodFactoryGenerator.kt, compiler/src/test/java/com/squareup/anvil/compiler/dagger/ProvidesMethodFactoryGeneratorTest.kt
=> Don't add the "Get" prefix to generated Factory classes, if the provider method name starts with "is"

compiler/src/main/java/com/squareup/anvil/compiler/Utils.kt, compiler/src/main/java/com/squareup/anvil/compiler/codegen/dagger/ProvidesMethodFactoryGenerator.kt, compiler/src/test/java/com/squareup/anvil/compiler/dagger/ProvidesMethodFactoryGeneratorTest.kt
The kotlin/java interop only omits "get-" if the `is` prefix is the _word_ "is", like `isAndroid` or `is_android`.
There's no special case for `isandroid`, `issues`, etc.
=> fix provides method names with an 'is-' prefix which is part of a longer word

compiler-utils/src/main/java/com/squareup/anvil/compiler/internal/DescriptorUtils.kt
Resolves #604 in a backward-compatible way. This saves needing to access the now-relocated `ErrorType` directly and also does a bit more thorough of a check
```kotlin
val KotlinType.isError: Boolean
get() = unwrap().let { unwrapped ->
unwrapped is ErrorType ||
(unwrapped is FlexibleType && unwrapped.delegate is ErrorType)
}
```
=> Use public isErrorType API for resolving error type checks

compiler-utils/src/main/java/com/squareup/anvil/compiler/internal/reference/AnnotationArgumentReference.kt, compiler-utils/src/main/java/com/squareup/anvil/compiler/internal/reference/ClassReference.kt, compiler-utils/src/main/java/com/squareup/anvil/compiler/internal/reference/PropertyReference.kt, compiler/src/test/java/com/squareup/anvil/compiler/internal/reference/PropertyReferenceTest.kt
=> create `PropertyReference.Psi` from primary constructor properties

compiler-utils/src/main/java/com/squareup/anvil/compiler/internal/PsiUtils.kt, compiler-utils/src/main/java/com/squareup/anvil/compiler/internal/reference/TypeReference.kt, compiler/src/test/java/com/squareup/anvil/compiler/dagger/InjectConstructorFactoryGeneratorTest.kt
=> When resolving `FqName`s check the inner class hierarchy for the right reference.

gradle-plugin/src/main/java/com/squareup/anvil/plugin/AnvilPlugin.kt, gradle-plugin/src/main/java/com/squareup/anvil/plugin/DisableIncrementalCompilationTask.kt
Don't share the output directory for the `DisableIncrementalCompilationTask`, if there are multiple Kotlin compilation tasks for the same module.
Fixes #602
=> Shared output directory

README.md
The second limitation was recently resolved leaving only one.
Resolves #637 .
=> Correct reference to number of limitations

compiler-utils/src/main/java/com/squareup/anvil/compiler/internal/PsiUtils.kt, compiler/src/test/java/com/squareup/anvil/compiler/dagger/BindsMethodValidatorTest.kt
Currently when something like @receiver:Qualifier is used on an extension function, the FqName utils don't have any cases to handle it and try to resolve the combined string of `@receiver:Qualifier ReceivingType` which results in us not finding the FqName for `ReceivingType`
=> Update FqName detection to fix validation of extension function bindings with qualifiers

compiler-utils/src/main/java/com/squareup/anvil/compiler/internal/PsiUtils.kt, compiler/src/test/java/com/squareup/anvil/compiler/dagger/BindsMethodValidatorTest.kt
This fixes validation of binding methods for types with back-ticked packages. Without this fix, the FqName cannot be found. In the test example, `Foo` would not have any super types found, and trying to resolve + get a reference for the binding method return type would result in an exception.
=> Handle back-ticked package names when resolving FqNames

compiler/src/main/java/com/squareup/anvil/compiler/codegen/dagger/BindsMethodValidator.kt, compiler/src/test/java/com/squareup/anvil/compiler/dagger/BindsMethodValidatorTest.kt
This should make it more obvious why a given binding failed without needing to check the generated code.
=> Improve the error message for failed binding validations when the parameter and return type do not match

CHANGELOG.md, compiler/src/main/java/com/squareup/anvil/compiler/codegen/BindingModuleGenerator.kt, compiler/src/test/java/com/squareup/anvil/compiler/codegen/BindingModuleGeneratorTest.kt, compiler/src/test/java/com/squareup/anvil/compiler/dagger/ProvidesMethodFactoryGeneratorTest.kt
If a class contributes multiple bindings and the bound types have the same short name, then Anvil would generate methods with duplicate names that clash in the end.
=> Fix duplicate generated binding method names.

CHANGELOG.md, compiler-utils/src/testFixtures/java/com/squareup/anvil/compiler/internal/testing/AnvilCompilation.kt
=> Add option to change the JVM target when testing code generators with the custom `AnvilCompilation` class

.github/workflows/ci.yml, build.gradle, buildSrc/settings.gradle, gradle-plugin/settings.gradle, gradle/libs.versions.toml, settings.gradle
The correct key wasn't used to override the version when the name uses camel case.
=> Fix version overrides.

compiler/generate_build_properties.gradle, gradle-plugin/generate_build_properties.gradle, integration-tests/tests/build.gradle
- Update our 'generateBuildProperties' tasks to be configuration cache compatible
- Remove an old task check around absolute file paths. The use of 'afterTask' causes failures when configuration cache is used, and Gradle's recommended replacement does not cleanly replace the deprecated method since it no longer provides access to the 'Task' instance. Based on previous comments around intention to remove this check, we should be fine without this.
=> Resolve Gradle configurations cache issues

gradle-plugin/src/main/java/com/squareup/anvil/plugin/AnvilPlugin.kt
Compiling a project with Anvil and K2 enabled would fail anyway, this just makes it more obvious that it's a known incompatibility for now.
=> Log an error when K2 is enabled until we support it

compiler/src/main/java/com/squareup/anvil/compiler/ModuleMergerIr.kt
Just a little cleanup to use more stable IR factory functions rather than direct impl types
=> Update some impl IR APIs to more modern alternatives

compiler/src/main/java/com/squareup/anvil/compiler/codegen/dagger/MapKeyCreatorGenerator.kt, integration-tests/library/build.gradle, integration-tests/library/src/main/java/com/squareup/anvil/test/MapBindings.kt, integration-tests/tests/src/test/java/com/squareup/anvil/test/MergeComponentTest.kt
=> Support explicit API mode for complex map keys

annotations-optional/build.gradle, annotations-optional/gradle.properties, annotations-optional/src/main/java/com/squareup/anvil/annotations/optional/ForScope.kt, annotations-optional/src/main/java/com/squareup/anvil/annotations/optional/SingleIn.kt, build.gradle, gradle-plugin/src/main/java/com/squareup/anvil/plugin/AnvilExtension.kt, gradle-plugin/src/main/java/com/squareup/anvil/plugin/AnvilPlugin.kt, gradle-plugin/src/main/java/com/squareup/anvil/plugin/VariantFilter.kt, settings.gradle
=> add optional annotations artifact with SingleIn and ForScope

gradle/libs.versions.toml, gradle/wrapper/gradle-wrapper.properties, integration-tests/mpp/android-module/build.gradle, sample/app/build.gradle, sample/app/src/main/AndroidManifest.xml
The AGP update becomes necessary in order to resolve:
```
Could not determine the dependencies of task ':sample:app:testDebugUnitTest'.
> Could not create task ':sample:app:processDebugResources'.
> Cannot use @TaskAction annotation on method IncrementalTask.taskAction$gradle_core() because interface org.gradle.api.tasks.incremental.IncrementalTaskInputs is not a valid parameter to an action method.
```
=> Gradle `8.3` and AGP `7.3.1`

compiler/src/main/java/com/squareup/anvil/compiler/codegen/dagger/ComponentDetectorCheck.kt, compiler/src/test/java/com/squareup/anvil/compiler/dagger/ComponentDetectorCheckTest.kt
This PR adds KSP support for ComponentDetectorCheck
- The changes to `ComponentDetectorCheck` follows the same pattern already used in `AnvilAnnotationDetectorCheck`. No additional logic/further changes have been introduced here.
- The corresponding test class was updated to handle for KSP and the current system by making the expected errors a bit more generic. Specifically, the error message returned during the test `a Dagger component causes an error` includes "Source0.kt:6" for KSP whereas it is "Source0.kt:6:11" for the current implementation. Similarly, the test `a Dagger component causes an error inner class` returns ":7" instead of ":7:13".
=> Update ComponentDetectorCheck for ksp

compiler-utils/src/testFixtures/java/com/squareup/anvil/compiler/internal/testing/AnvilCompilation.kt, compiler/src/main/java/com/squareup/anvil/compiler/codegen/dagger/AnvilMergeAnnotationDetectorCheck.kt, compiler/src/test/java/com/squareup/anvil/compiler/dagger/AnvilMergeAnnotationDetectorCheckTest.kt
This PR adds KSP support for `AnvilMergeAnnotationDetector`
- The changes to `AnvilMergeAnnotationDetector` follows the same pattern already used in AnvilAnnotationDetectorCheck. 
- Added `kspArgs["disable-component-merging"]` to `AnvilCompilation.kt` when mode=KSP, this is to resolve an issue where the annotations `@merge<component/subcompnent/module/Interface>` where being ignored.
- The corresponding test class was updated to handle KSP and the current system by making the expected errors a bit more generic. Specifically, the error message includes "Source0.kt:6" for KSP whereas it is "Source0.kt:6:7" for the current implementation.
=> Update AnvilMergeAnnotationDetector for ksp

gradle-plugin-build-logic/build.gradle, gradle-plugin-build-logic/gradle.properties
The symlinked properties file caused issues with syncing in Windows.
https://github.com/square/anvil/pull/763#discussion_r1379563691
=> replace the symlinked `gradle.properties` with manually-loaded Properties

.github/workflows/ci.yml
https://github.com/re-actors/alls-green
One shard requires that all the others are green or skipped.  This single shard can be added as a required check in GitHub's branch protection rules, then never touched again.  When adding a new shard to the workflow, you just add its name to the "needs" list and you're done.
And yes, it supports matrix strategies without needing to maintain a list of all the permutations.
=> Add an `all-checks` capstone shard to CI

build-logic/src/main/kotlin/com/squareup/anvil/KtlintConventionPlugin.kt, build-logic/src/main/kotlin/com/squareup/anvil/RootPlugin.kt, integration-tests/code-generator-tests/src/test/java/com/squareup/anvil/test/GeneratedCodeTest.kt, integration-tests/code-generator/src/main/java/com/squareup/anvil/test/TestCodeGenerator.kt, integration-tests/code-generator/src/main/java/com/squareup/anvil/test/TestWithKaptCodeGenerator.kt, integration-tests/code-generator/src/test/java/com/squareup/anvil/test/TestCodeGeneratorTest.kt, integration-tests/library/src/main/java/com/squareup/anvil/test/AssistedService.kt, integration-tests/library/src/main/java/com/squareup/anvil/test/Bindings.kt, integration-tests/library/src/main/java/com/squareup/anvil/test/ContributedSubcomponent.kt, integration-tests/library/src/main/java/com/squareup/anvil/test/Modules.kt, integration-tests/library/src/main/java/com/squareup/anvil/test/PriorityBindings.kt, integration-tests/tests/src/test/java/com/squareup/anvil/test/AssistedInjectionTest.kt, integration-tests/tests/src/test/java/com/squareup/anvil/test/MergeComponentTest.kt, integration-tests/tests/src/test/java/com/squareup/anvil/test/MergeModulesTest.kt, sample/app/src/androidTest/java/com/squareup/anvil/sample/FakeFatherProvider.kt, sample/app/src/androidTest/java/com/squareup/anvil/sample/TestRunner.kt, sample/app/src/main/java/com/squareup/anvil/sample/RandomModule.kt, sample/library/src/main/java/com/squareup/anvil/sample/God.kt
It will be applied everywhere with the new convention plugins, but it hasn't been since [(#763)](https://github.com/square/anvil/pull/763) landed.  Since we now add trailing commas, there's a bit of a diff.
=> Apply KtLint to the unpublished modules

gradle/libs.versions.toml
This reverts commit e068cd87ec922754943473b6bdfba88402bb0eaf.
There was an uncaught merge conflict between https://github.com/square/anvil/pull/793 and https://github.com/square/anvil/pull/795. This reverts the KotlinPoet bump to get main back to green and we can look at the failures separately as part of re-bumping the version.
=> Revert "Update kotlinpoet to v1.15.3"

build-logic/conventions/src/main/kotlin/com/squareup/anvil/benchmark/CreateBenchmarkProjectTask.kt, build-logic/settings/src/main/kotlin/com/squareup/anvil/builds/settings/SettingsPlugin.kt
The benchmark project/build is now a standalone build, instead of being subprojects in the main 'anvil' build. As such, it needs its own Gradle Wrapper jar, or the profiler scenarios will default to the version used to build the profiler.
=> Copy the root `gradle` directory during benchmark project generation

build-logic/conventions/src/main/kotlin/com/squareup/anvil/conventions/CompositePlugin.kt, build-logic/conventions/src/main/kotlin/com/squareup/anvil/conventions/utils/task.kt
Prior to `1.9.20`, KGP had this convenience extension for getting any domain object's extra properties:
```kotlin
inline val Any.extraProperties: ExtraPropertiesExtension
get() = (this as ExtensionAware).extensions.extraProperties
```
It worked under normal circumstances because Gradle's generated decorated classes all implement `ExtensionAware`, even when the original type in the source code does not.
In `1.9.20`, that extension is changed to this:
```kotlin
inline val ExtensionAware.extraProperties: ExtraPropertiesExtension
get() = extensions.extraProperties
```
So no more foot-gun, but existing usages that were unsafe will no longer resolve.
=> Update usage of KGP's `Any.extraProperties` extension for `1.9.20`+

.github/workflows/ci.yml, annotations-optional/api/annotations-optional.api, annotations/api/annotations.api, build-logic/conventions/build.gradle, build-logic/conventions/src/main/kotlin/com/squareup/anvil/conventions/LibraryPlugin.kt, compiler-api/api/compiler-api.api, compiler-utils/api/compiler-utils.api, compiler/api/compiler.api, gradle-plugin/api/gradle-plugin.api, gradle/libs.versions.toml
https://github.com/Kotlin/binary-compatibility-validator
=> Add the kotlinx binary compatibility plugin

build-logic/conventions/src/main/kotlin/com/squareup/anvil/conventions/BasePlugin.kt, build-logic/conventions/src/main/kotlin/com/squareup/anvil/conventions/LibraryPlugin.kt, build-logic/conventions/src/main/kotlin/com/squareup/anvil/conventions/RootPlugin.kt, build-logic/conventions/src/main/kotlin/com/squareup/anvil/conventions/utils/project.kt, build-logic/delegate/settings.gradle.kts
We been getting flakes in CI like this one:
```
> Cannot access output property 'outputDir' of task ':gradle-plugin:generateGradleTestBuildConfig'. Accessing unreadable inputs or outputs is not supported. Declare the task as untracked by using Task.doNotTrackState(). [...]
> Failed to create MD5 hash for file '/home/runner/work/anvil/anvil/gradle-plugin/build/generated/sources/buildConfig/gradleTest/com/squareup/anvil/plugin/buildProperties/BuildProperties.kt' as it does not exist.
```
These are happening because the projects in the main "anvil" build are technically part of two different Gradle builds -- the main/root one, and the one that's included by the `:delegate` build.  Both of those builds are acting upon the same files, and Gradle doesn't share concurrency controls between its …
=> Use a different build directory per Gradle build for main-build projects

gradle-plugin/api/gradle-plugin.api, gradle-plugin/src/gradleTest/java/com/squareup/anvil/plugin/AnvilExtensionTest.kt, gradle-plugin/src/main/java/com/squareup/anvil/plugin/AnvilExtension.kt
This change makes it so that all of Anvil's existing configuration options can be set via a `gradle.properties` or a `-P_______` command line option.
For any setting, Anvil take the first non-null value out of:
1. Settings in the Gradle DSL:
```kotlin
anvil {
generateDaggerFactories.set(true)
}
```
3. Properties set via the command line like:
```sh
./gradlew build -Pcom.squareup.anvil.generateDaggerFactories=true
```
4. Properties specified in a project-level, root-project-level, or `~/.gradle/`-level `gradle.properties`:
```properties
com.squareup.anvil.generateDaggerFactories = true
```
5. Hard-coded default values (never null)
Practically speaking, this makes it possible to *locally* feature-toggle things (like the upcoming incremental fix) without touching a project's build logic.
=> binding extension properties to Gradle properties

integration-tests/mpp/android-module/build.gradle.kts
We were using `android()` for the sake of Kotlin 1.8.22 support in CI. Since that's no longer supported,
we can update the build file and lose the warning in the terminal.
The warning was:
```
> Configure project :delegate:integration-tests:mpp:android-module
w: Please use `androidTarget` function instead of `android` to configure android target inside `kotlin { }` block.
```
=> replace deprecated use of `android()` with `androidTarget()`

.editorconfig, .github/workflows/ci.yml, .github/workflows/release.yml, renovate.json
1. Anvil's codestyle for .yml requires a space before a colon in `.yml`.  That's valid syntax, but Renovate can't parse it -- which means we don't get updates for Actions dependencies.
2. The `config:base` in `renovate.json` is actually deprecated.  Its replacement is `config:recommended`, except that they [actually recommend](https://docs.renovatebot.com/upgrade-best-practices/#use-the-configbest-practices-preset) using `config:best-practices`.
=> Renovate `best-practices` preset & making Renovate work with workflow files 

.github/workflows/ci.yml, .github/workflows/publish-snapshot.yml
This allows us to manually trigger a publish-snapshot build against a different branch.
=> move snapshot publishing into its own workflow

compiler/src/main/java/com/squareup/anvil/compiler/codegen/incremental/GeneratedFileCache.kt, compiler/src/test/java/com/squareup/anvil/compiler/codegen/CodeGenerationExtensionTest.kt, compiler/src/test/java/com/squareup/anvil/compiler/codegen/incremental/GeneratedFileCacheTest.kt, gradle-plugin/src/gradleTest/java/com/squareup/anvil/plugin/IncrementalTest.kt
fixes #880
The `GeneratedFileCache` needs a reference to the current machine's project directory and the path of its binary file.
These values were being written to that binary file and restored on subsequent reads. That breaks things when the same cache is used on a different machine due to remote build caching.
Now, those two files are still part of `GeneratedFileCache`, but only the inner `Tables` class is actually cached.
=> Don't cache the `projectDir` or `binaryFile` as part of `GeneratedFileCache`

build-logic/conventions/src/main/kotlin/com/squareup/anvil/conventions/KtlintConventionPlugin.kt, compiler-utils/api/compiler-utils.api, compiler-utils/src/main/java/com/squareup/anvil/compiler/internal/reference/ClassReference.kt, compiler-utils/src/main/java/com/squareup/anvil/compiler/internal/reference/TypeReference.kt, compiler/src/main/java/com/squareup/anvil/compiler/codegen/dagger/BindsMethodValidator.kt, compiler/src/test/java/com/squareup/anvil/compiler/dagger/BindsMethodValidatorTest.kt
Reverts square/anvil#833
see ([#833](https://github.com/square/anvil/issues/885)).
"Assignable" checks aren't working for most generic type references, and it doesn't seem to be a quick fix.
=> Revert "[bugfix] Binding supertype which is narrower than return type is wrongly allowed"

compiler/src/main/java/com/squareup/anvil/compiler/Utils.kt, compiler/src/main/java/com/squareup/anvil/compiler/codegen/CodeGenerationExtension.kt, compiler/src/main/java/com/squareup/anvil/compiler/codegen/incremental/FileCacheOperations.kt
If we make any changes while syncing the local state with our internal cache, that will affect the source files and PSI parsing, but it doesn't affect the state represented by the ModuleDescriptor.  In order to get things in sync, we need to return a `RetryWithAdditionalRoots`.
While doing that analysis, the compiler will also sync its own files -- which means it will delete any `.class` files that are no longer current.
See discussion here: https://github.com/square/anvil/pull/877#discussion_r1517184297
=> Immediately re-run analysis if cache restoration generated changes

compiler/src/main/java/com/squareup/anvil/compiler/Utils.kt, compiler/src/main/java/com/squareup/anvil/compiler/codegen/CodeGenerationExtension.kt, compiler/src/main/java/com/squareup/anvil/compiler/codegen/incremental/FileCacheOperations.kt, compiler/src/main/java/com/squareup/anvil/compiler/codegen/incremental/GeneratedFileCache.kt, compiler/src/test/java/com/squareup/anvil/compiler/codegen/incremental/CacheTestEnvironment.kt, compiler/src/test/java/com/squareup/anvil/compiler/codegen/incremental/FileCacheOperationsTest.kt, gradle-plugin/src/gradleTest/java/com/squareup/anvil/plugin/IncrementalTest.kt, gradle-plugin/src/gradleTest/java/com/squareup/anvil/plugin/testing/AnvilGradleTestEnvironment.kt
fixes #898
By "input `KtFile`s" I'm referring to the `files: List<KtFile>` parameters in `CodeGeneratorExtension.doAnalysis(...)` and `CodeGeneratorExtension.onAnalysisCompleted(...)`.
For any given compilation, on the very first round of analysis/generation, the `files` parameter will roughly correspond to the incremental files from Gradle's `InputChanges` instance.
We should treat these files as changed because:
1. If they're also in our internal cache, with the same contents (MD5 hash), then there must be some reason that Gradle decided to pass them as input again and the compiler agreed. This is most likely because of a classpath change, either in a dependency project or an external library.
In this case, since Anvil uses classpath discovery to generate binding modules and merged …
=> treat any input `KtFile`s as changed/invalidated

renovate.json
[docs](https://docs.renovatebot.com/configuration-options/#rebasewhen)
The `conflicted` setting is copy-pasta from one of my projects where I use Kodiak to handle updating/merging.  Without Kodiak, it just means we have to babysit the PRs.
=> switch Renovate's `rebaseWhen` setting to `auto`

.github/workflows/ci.yml, build-logic/conventions/src/main/kotlin/com/squareup/anvil/conventions/KtlintConventionPlugin.kt, gradle-plugin/api/gradle-plugin.api, gradle-plugin/build.gradle.kts, gradle-plugin/src/gradleTest/java/com/squareup/anvil/plugin/AnvilExtensionTest.kt, gradle-plugin/src/gradleTest/java/com/squareup/anvil/plugin/IncrementalTest.kt, gradle-plugin/src/gradleTest/java/com/squareup/anvil/plugin/LifecycleTest.kt, gradle-plugin/src/gradleTest/java/com/squareup/anvil/plugin/testing/AnvilExtensionSpec.kt, gradle-plugin/src/gradleTest/java/com/squareup/anvil/plugin/testing/AnvilFilePathExtensions.kt, gradle-plugin/src/gradleTest/java/com/squareup/anvil/plugin/testing/AnvilGradleTestEnvironment.kt, gradle-plugin/src/gradleTest/java/com/squareup/anvil/plugin/testing/AnvilVersionMatrix.kt, gradle-plugin/src/main/java/com/squareup/anvil/plugin/AnvilExtension.kt
The new code manages to be configuration-cache-safe without needing the Project parameter.  I added cases for KSP generation to the Gradle tests in `LifecycleTest`.
=> Remove the `Project` parameter from `AnvilExtension.useKsp(...)`

compiler/src/main/java/com/squareup/anvil/compiler/codegen/ContributesSubcomponentCodeGen.kt, compiler/src/test/java/com/squareup/anvil/compiler/codegen/ContributesSubcomponentGeneratorTest.kt
Currently any `@ContributesSubcomponent.Factory` that is an interface fails the KSP codegen with "A factory must have exactly one abstract function returning the subcomponent ...".  The `getAllFunctions()` returns non abstract methods like equals/hashCode for interfaces, so we need to filter for interfaces as well.
=> fix interface based @ContributesSubcomponent.Factory in KSP

compiler-utils/src/testFixtures/java/com/squareup/anvil/compiler/internal/testing/SimpleCodeGenerator.kt, compiler/src/main/java/com/squareup/anvil/compiler/codegen/CodeGenerationExtension.kt, compiler/src/test/java/com/squareup/anvil/compiler/codegen/CodeGenerationExtensionTest.kt, compiler/src/test/java/com/squareup/anvil/compiler/testing/AnvilCompilationModeTest.kt, compiler/src/test/java/com/squareup/anvil/compiler/testing/CompilationEnvironment.kt
If the incremental syncing logic at the start of compilation results in any file changes, return early without actually generating code (in that round). The compiler will do another incremental compilation, returning an updated set of source files and a ModuleDescriptor that reflects any deleted or added files since the previous round.
=> re-run analysis between an incremental sync and code generation

compiler/src/main/java/com/squareup/anvil/compiler/codegen/CodeGenerationExtension.kt, compiler/src/main/java/com/squareup/anvil/compiler/codegen/ContributesSubcomponentHandlerGenerator.kt, compiler/src/test/java/com/squareup/anvil/compiler/codegen/ContributesSubcomponentHandlerGeneratorTest.kt
The `ContributesSubcomponentHandlerGenerator` is responsible for generating these:
```kotlin
@MergeSubcomponent(scope = Any::class)
public interface SubcomponentInterfaceA : SubcomponentInterface {
// ...
}
```
It used to generate those interfaces as soon as it scanned the triggers, but that can cause problems if another `@ContributesSubcomponent` interface is being generated, and that intends to replace a human-written one.
Now, the handler is a `PrivateCodeGenerator` and it doesn't start parsing/generating until all the "public" code generation is done.  This means it gets the full picture of the possible graph, but it still finishes generating before any IR merging happens.
=> delay `@ContributesSubcomponent` generation until the last analysis rounds

compiler/src/main/java/com/squareup/anvil/compiler/codegen/ContributesSubcomponentCodeGen.kt
After looking further, it's not possible to use just declared functions. Fortunately the pathological case (traversing lots of supertypes) is probably also an error case
=> Remove comment

compiler/build.gradle.kts, compiler/src/test/java/com/squareup/anvil/compiler/TestUtils.kt, compiler/src/test/java/com/squareup/anvil/compiler/dagger/AnvilAnnotationDetectorCheckTest.kt, compiler/src/test/java/com/squareup/anvil/compiler/dagger/AnvilMergeAnnotationDetectorCheckTest.kt, compiler/src/test/java/com/squareup/anvil/compiler/dagger/AssistedFactoryGeneratorTest.kt, compiler/src/test/java/com/squareup/anvil/compiler/dagger/AssistedInjectGeneratorTest.kt, compiler/src/test/java/com/squareup/anvil/compiler/dagger/BindsMethodValidatorTest.kt, compiler/src/test/java/com/squareup/anvil/compiler/dagger/ComponentDetectorCheckTest.kt, compiler/src/test/java/com/squareup/anvil/compiler/dagger/MapKeyCreatorGeneratorTest.kt, compiler/src/test/java/com/squareup/anvil/compiler/dagger/MembersInjectorGeneratorTest.kt, compiler/src/test/java/com/squareup/anvil/compiler/dagger/ProvidesMethodFactoryGeneratorTest.kt, compiler/src/test/java/com/squareup/anvil/compiler/testing/CompilationEnvironment.kt
prompted by https://github.com/square/anvil/pull/934#discussion_r1544638830
Before this change, `allWarningsAsErrors` defaulted to `false` locally but `true` in CI.  We don't really gain anything by ignoring those warnings locally, since the relevant code is so isolated.
Note that the public `compileAnvil(...)` function in our test fixtures ([link](https://github.com/square/anvil/blob/a1def6af59ec11b9d92426947f8c833fb27e7bde/compiler-utils/src/testFixtures/java/com/squareup/anvil/compiler/internal/testing/AnvilCompilation.kt#L251)) defaults to `false`, but now our internal `compile(...)` from `TestUtils` now defaults to `true`.  That avoids a breaking change.
=> always use `-Werror` in internal KCT compilations

compiler/src/main/java/com/squareup/anvil/compiler/codegen/reference/RealAnvilModuleDescriptor.kt, compiler/src/test/java/com/squareup/anvil/compiler/codegen/ContributesSubcomponentHandlerGeneratorTest.kt, compiler/src/test/java/com/squareup/anvil/compiler/internal/reference/AnnotationReferenceTest.kt, compiler/src/test/java/com/squareup/anvil/compiler/internal/reference/RealAnvilModuleDescriptorTest.kt, compiler/src/test/java/com/squareup/anvil/compiler/internal/reference/ReferencesTestEnvironment.kt
=> pass files with only top-level function/property declarations to `CodeGenerator` implementations

CHANGELOG.md, annotations/api/annotations.api, annotations/src/main/java/com/squareup/anvil/annotations/ContributesBinding.kt, annotations/src/main/java/com/squareup/anvil/annotations/internal/InternalBindingMarker.kt, compiler/src/main/java/com/squareup/anvil/compiler/ContributedBinding.kt, compiler/src/main/java/com/squareup/anvil/compiler/IrContributionMerger.kt, compiler/src/main/java/com/squareup/anvil/compiler/codegen/AnnotationReferenceExtensions.kt, compiler/src/main/java/com/squareup/anvil/compiler/codegen/ContributesBindingCodeGen.kt, compiler/src/main/java/com/squareup/anvil/compiler/codegen/Contribution.kt, compiler/src/main/java/com/squareup/anvil/compiler/codegen/ksp/KSAnnotationExtensions.kt, compiler/src/test/java/com/squareup/anvil/compiler/codegen/BindingModulePriorityTest.kt, compiler/src/test/java/com/squareup/anvil/compiler/codegen/ContributesBindingGeneratorTest.kt, integration-tests/library/src/main/java/com/squareup/anvil/test/PriorityBindings.kt, integration-tests/tests/src/test/java/com/squareup/anvil/test/MergeComponentTest.kt
This makes the broader `enum` -> `Int` change source-compatible.
The IDE's auto-replace only partly works, because the deprecated `ContributesBinding.priority` parameter only works as documentation. Devs can auto-replace the enum entry with the corresponding integer, but if they're using a named argument, it will wind up with something like `priority = RANK_NORMAL`.
=> rename the new int-based priority to `rank`, restore the enum to `priority`

compiler/src/main/java/com/squareup/anvil/compiler/codegen/dagger/ProvidesMethodFactoryCodeGen.kt
Noticed this warning in the IDE, it's functionally an else block because it's always true here. Left the condition in a comment for clarity
=> Simplify redundant logic

compiler-utils/src/testFixtures/java/com/squareup/anvil/compiler/internal/testing/AnvilCompilation.kt, compiler/src/test/java/com/squareup/anvil/compiler/InterfaceMergerRepeatableTest.kt, compiler/src/test/java/com/squareup/anvil/compiler/InterfaceMergerTest.kt, compiler/src/test/java/com/squareup/anvil/compiler/MergeModulesTest.kt, compiler/src/test/java/com/squareup/anvil/compiler/ModuleMergerRepeatableTest.kt, compiler/src/test/java/com/squareup/anvil/compiler/ModuleMergerTest.kt, compiler/src/test/java/com/squareup/anvil/compiler/TestUtils.kt, compiler/src/test/java/com/squareup/anvil/compiler/codegen/BindingModuleCodegenTest.kt, compiler/src/test/java/com/squareup/anvil/compiler/codegen/BindingModuleMultibindingMapTest.kt, compiler/src/test/java/com/squareup/anvil/compiler/codegen/BindingModuleMultibindingSetTest.kt, compiler/src/test/java/com/squareup/anvil/compiler/codegen/BindingModulePriorityTest.kt, compiler/src/test/java/com/squareup/anvil/compiler/codegen/CodeGenerationExtensionTest.kt, compiler/src/test/java/com/squareup/anvil/compiler/codegen/ContributesBindingGeneratorTest.kt, compiler/src/test/java/com/squareup/anvil/compiler/codegen/ContributesMultibindingGeneratorTest.kt, compiler/src/test/java/com/squareup/anvil/compiler/codegen/ContributesSubcomponentGeneratorTest.kt, compiler/src/test/java/com/squareup/anvil/compiler/codegen/ContributesSubcomponentHandlerGeneratorTest.kt, compiler/src/test/java/com/squareup/anvil/compiler/codegen/ContributesToCodeGenTest.kt, compiler/src/test/java/com/squareup/anvil/compiler/dagger/AssistedFactoryGeneratorTest.kt, compiler/src/test/java/com/squareup/anvil/compiler/dagger/AssistedInjectGeneratorTest.kt, compiler/src/test/java/com/squareup/anvil/compiler/dagger/BindsMethodValidatorTest.kt, compiler/src/test/java/com/squareup/anvil/compiler/dagger/ComponentDetectorCheckTest.kt, compiler/src/test/java/com/squareup/anvil/compiler/dagger/InjectConstructorFactoryGeneratorTest.kt, compiler/src/test/java/com/squareup/anvil/compiler/dagger/MembersInjectorGeneratorTest.kt, compiler/src/test/java/com/squareup/anvil/compiler/dagger/ProvidesMethodFactoryGeneratorTest.kt, compiler/src/test/java/com/squareup/anvil/compiler/testing/CompilationEnvironment.kt
The published `AnvilCompilation` logic gets a new `expectExitCode: ExitCode? = null` parameter.  If a value is specified, the assertion is done before executing the `block` lambda.
In our internal delegating `compile(...)` functions, the parameter becomes non-nullable and defaults to `ExitCode.OK`.
This is done in follow-up to [this](https://github.com/square/anvil/pull/934#discussion_r1544638830) comment.
=> Default to asserting that `exitCode == OK` in all internal tests

.github/workflows/publish-snapshot.yml, RELEASING.md
The suggestion came from @gabrielittner here: https://github.com/square/anvil/pull/866#discussion_r1484817963
=> Set branch-specific SNAPSHOT version names in non-main snapshot releases

.github/workflows/ci.yml
M1 runners now seem to be the default for `macos-latest`:
[CI run](https://github.com/square/anvil/actions/runs/8808676517/job/24199009273?pr=979)
[logs](https://productionresultssa9.blob.core.windows.net/actions-results/c4ab73b8-2cb0-45d4-9053-d27cbdebbec4/workflow-job-run-e63755f8-096f-5d22-f83b-af41e271b2be/logs/job/job-logs.txt?rsct=text%2Fplain&se=2024-04-24T15%3A17%3A59Z&sig=S0BML9se1w5EGdNwc7rHup6Bur00%2B3qCkgYdCmc3OGo%3D&sp=r&spr=https&sr=b&st=2024-04-24T15%3A07%3A54Z&sv=2021-12-02)
```
Current runner version: '2.315.0'
Operating System
macOS
14.4.1
23E224
Runner Image
Image: macos-14-arm64
Version: 20240415.6
Included Software: https://github.com/actions/runner-images/blob/macos-14-arm64/20240415.6/images/macos/macos-14-arm64-Readme.md
Image Release: …
```
=> handle GitHub's switch to M1 macs for `macos-latest` runners

CHANGELOG.md, compiler-utils/src/testFixtures/java/com/squareup/anvil/compiler/internal/testing/AnvilCompilation.kt, compiler/src/main/java/com/squareup/anvil/compiler/AnvilCommandLineProcessor.kt, compiler/src/main/java/com/squareup/anvil/compiler/AnvilComponentRegistrar.kt, compiler/src/main/java/com/squareup/anvil/compiler/IrContributionMerger.kt, gradle-plugin/src/gradleTest/java/com/squareup/anvil/plugin/IncrementalTest.kt, gradle-plugin/src/gradleTest/java/com/squareup/anvil/plugin/testing/FileStubs.kt, gradle-plugin/src/gradleTest/java/com/squareup/anvil/plugin/testing/classGraph.kt, gradle-plugin/src/main/java/com/squareup/anvil/plugin/AnvilPlugin.kt
KGP's "classpath snapshot" incremental logic uses a previous build's `.class` files to track references and invalidate files.  Assume there are two projects: `:lib1` and `:lib2`.  `:lib2` depends on `:lib1`.  If a change is made to an existing type in `:lib1` since the last successful build, KGP will inspect the snapshot of `:lib2`'s class files to see if it references anything in `:lib1`.  If `:lib2` didn't already reference `:lib1`, then the `:lib2:compileKotlin` task will be treated as `UP_TO_DATE` and will not execute again.
Anvil's module and interface merging logic only changes the IR symbols.  This means that all merged references are added to the resultant binary, but not to class files.  Those changes are invisible to the classpath snapshots.  This is why we disable incremental …
=> fix incremental behavior when the compilation target has IR merging but no KAPT stub generation

compiler/src/main/java/com/squareup/anvil/compiler/ContributedBinding.kt, compiler/src/main/java/com/squareup/anvil/compiler/codegen/AnnotationReferenceExtensions.kt, compiler/src/main/java/com/squareup/anvil/compiler/codegen/Contribution.kt, compiler/src/main/java/com/squareup/anvil/compiler/codegen/ksp/KSAnnotationExtensions.kt, compiler/src/test/java/com/squareup/anvil/compiler/TestUtils.kt, compiler/src/test/java/com/squareup/anvil/compiler/codegen/BindingModuleQualifierTest.kt, compiler/src/test/java/com/squareup/anvil/compiler/codegen/ContributesMultibindingGeneratorTest.kt, compiler/src/test/java/com/squareup/anvil/compiler/testing/AnvilAnnotationsTest.kt
=> consider `ignoreQualifier` arguments when checking for duplicate bindings

CHANGELOG.md, compiler-utils/api/compiler-utils.api, compiler-utils/src/main/java/com/squareup/anvil/compiler/internal/reference/AnnotationArgumentReference.kt, compiler-utils/src/main/java/com/squareup/anvil/compiler/internal/reference/ClassReference.kt, compiler-utils/src/main/java/com/squareup/anvil/compiler/internal/reference/MemberPropertyReference.kt, compiler/src/main/java/com/squareup/anvil/compiler/codegen/ContributesSubcomponentCodeGen.kt, compiler/src/main/java/com/squareup/anvil/compiler/codegen/ContributesSubcomponentHandlerGenerator.kt, compiler/src/main/java/com/squareup/anvil/compiler/codegen/dagger/AssistedFactoryCodeGen.kt, compiler/src/main/java/com/squareup/anvil/compiler/codegen/dagger/BindsMethodValidator.kt, compiler/src/main/java/com/squareup/anvil/compiler/codegen/dagger/DaggerGenerationUtils.kt, compiler/src/main/java/com/squareup/anvil/compiler/codegen/dagger/MapKeyCreatorCodeGen.kt, compiler/src/main/java/com/squareup/anvil/compiler/codegen/dagger/MembersInjectorCodeGen.kt, compiler/src/main/java/com/squareup/anvil/compiler/codegen/dagger/ProvidesMethodFactoryCodeGen.kt, compiler/src/main/java/com/squareup/anvil/compiler/codegen/reference/RealAnvilModuleDescriptor.kt, compiler/src/test/java/com/squareup/anvil/compiler/codegen/ContributesSubcomponentGeneratorTest.kt, compiler/src/test/java/com/squareup/anvil/compiler/internal/reference/ClassReferenceTest.kt, compiler/src/test/java/com/squareup/anvil/compiler/internal/reference/MemberFunctionReferenceTest.kt, compiler/src/test/java/com/squareup/anvil/compiler/internal/reference/MemberPropertyReferenceTest.kt, compiler/src/test/java/com/squareup/anvil/compiler/internal/reference/ReferencesTestEnvironment.kt, compiler/src/test/java/com/squareup/anvil/compiler/internal/reference/TypeReferenceTest.kt
fixes #1003
Our checks for a single abstract method in a `@ContributesSubcomponent.Factory`-annotated interface do not consider functions that are defined in a supertype.  The existing `ClassReference.functions` property was somewhat ambiguously named, which probably contributed to the error.
=> include inherited functions in Subcomponent Factory checks

compiler-utils/api/compiler-utils.api, compiler-utils/src/main/java/com/squareup/anvil/compiler/internal/reference/ClassReference.kt, compiler-utils/src/main/java/com/squareup/anvil/compiler/internal/reference/MemberFunctionReference.kt, compiler-utils/src/main/java/com/squareup/anvil/compiler/internal/reference/TypeReference.kt, compiler-utils/src/main/java/com/squareup/anvil/compiler/internal/reference/Visibility.kt, compiler/src/main/java/com/squareup/anvil/compiler/codegen/ContributesSubcomponentCodeGen.kt, compiler/src/main/java/com/squareup/anvil/compiler/codegen/ContributesSubcomponentHandlerGenerator.kt, compiler/src/main/java/com/squareup/anvil/compiler/codegen/dagger/DaggerGenerationUtils.kt, compiler/src/test/java/com/squareup/anvil/compiler/codegen/ContributesSubcomponentGeneratorTest.kt, compiler/src/test/java/com/squareup/anvil/compiler/dagger/MembersInjectorGeneratorTest.kt, compiler/src/test/java/com/squareup/anvil/compiler/internal/reference/ClassReferenceTest.kt, compiler/src/test/java/com/squareup/anvil/compiler/internal/reference/ReferencesTestEnvironment.kt
Fixes two bugs where we were using a type variable name (e.g., `T`) instead of resolving the actual type.
fixes #1040
fixes #1041
=> generic type resolution fixes

compiler-utils/src/testFixtures/java/com/squareup/anvil/compiler/internal/testing/AnvilCompilation.kt
The internals of `compileAnvil` contain a [KotlinCompilation](https://github.com/ZacSweers/kotlin-compile-testing/blob/fc96a2c58740a4ac6feb688cf661ef7d755b650b/core/src/main/kotlin/com/tschuchort/compiletesting/AbstractKotlinCompilation.kt#L104) instance which provides a parameter for the kotlin language version. This PR is simply surfacing access to set this param from `compileAnvil(...)` so that other versions of Kotlin can be targeted in tests other than the default. Eg: allows specifying Kotlin 1.9 when using Kotlin 2.0
Example:
```kotlin
// Run with Kotlin 2.0.XX
@Test
fun `target kotlin 1.9`() {
compileAnvil(
"""
package com.example
import com.mine.InjectWith
import com.mine.InitializedScope
@InjectWith(InitializedScope::class)
class MyTestActivity : FakeBaseActivity() …
```
=> Surface Kotlin language version param (kotlinLanguageVersion) in compileAnvil() compile-utils function

gradle-plugin/api/gradle-plugin.api, gradle-plugin/src/gradleTest/java/com/squareup/anvil/plugin/DaggerFactoryGenerationDetectionTest.kt, gradle-plugin/src/gradleTest/java/com/squareup/anvil/plugin/LifecycleTest.kt, gradle-plugin/src/main/java/com/squareup/anvil/plugin/AnvilExtension.kt, gradle-plugin/src/main/java/com/squareup/anvil/plugin/AnvilPlugin.kt, gradle-plugin/src/main/java/com/squareup/anvil/plugin/VariantFilter.kt
This is grabbed from the [Kotlin 2.0.21](https://github.com/square/anvil/tree/joel.kotlin-2.0.21) branch, since we want to disable the KSP apis in 2.5.0 as well.
=> Hide api for enabling KSP for upcoming release because it's currently only a partial implementation in the main Anvil repo

.github/workflows/ci.yml
Using --no-parallel to avoid:
https://youtrack.jetbrains.com/issue/KT-74241/Dependency-locking-sometimes-fails-with-gradle-kotlin-plugin https://youtrack.jetbrains.com/issue/KT-74394/KGP-isolated-projects-Something-has-been-appended-to-this-collector-already
https://github.com/square/anvil/actions/runs/13141745288/job/36670332186
```
1: Task failed with an exception.
-----------
> Task :compiler-api:dependencyGuard
* What went wrong:
Execution failed for task ':compiler:dependencyGuard'.
> Something has been appended to this collector already
* Try:
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.
* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task …
```
=> avoid dependency-guard dependency locking flakes in CI

compiler-testing/src/main/kotlin/com/squareup/anvil/compiler/testing/compilation/Compile2.kt
The kotlin `LanguageVersion` determines which API's to use, but the actual Kotlin library version is what determines what flags it understands.
=> determine kapt flag name by kotlin version instead of language version

compiler-k2/src/main/kotlin/com/squareup/anvil/compiler/k2/fir/merging/AnvilFirAnnotationMergingExtension.kt, compiler-k2/src/test/kotlin/com/squareup/anvil/compiler/k2/fir/FirCanaryTest.kt, compiler-k2/src/test/kotlin/com/squareup/anvil/compiler/k2/fir/contributions/ContributesBindingFirExtensionTest.kt, compiler-testing/api/compiler-testing.api, compiler-testing/src/main/kotlin/com/squareup/anvil/compiler/testing/classgraph/classInfo.kt
This is effectively a POC integration between the two for now to work around needing multiple compilation rounds for the way we pick up the modules in K1.
=> Include generated Dagger modules from @ContributesBinding when merging modules
